/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput{}

// GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput struct for GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput
type GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput struct {
	BypassCode *string `json:"bypass_code,omitempty"`
	DeviceTrustToken *string `json:"device_trust_token,omitempty"`
	Email string `json:"email"`
	Ip string `json:"ip"`
	Password string `json:"password"`
	UserAgent string `json:"user_agent"`
}

type _GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput

// NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput instantiates a new GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput(email string, ip string, password string, userAgent string) *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput {
	this := GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput{}
	this.Email = email
	this.Ip = ip
	this.Password = password
	this.UserAgent = userAgent
	return &this
}

// NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInputWithDefaults instantiates a new GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInputWithDefaults() *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput {
	this := GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput{}
	return &this
}

// GetBypassCode returns the BypassCode field value if set, zero value otherwise.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetBypassCode() string {
	if o == nil || IsNil(o.BypassCode) {
		var ret string
		return ret
	}
	return *o.BypassCode
}

// GetBypassCodeOk returns a tuple with the BypassCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetBypassCodeOk() (*string, bool) {
	if o == nil || IsNil(o.BypassCode) {
		return nil, false
	}
	return o.BypassCode, true
}

// HasBypassCode returns a boolean if a field has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) HasBypassCode() bool {
	if o != nil && !IsNil(o.BypassCode) {
		return true
	}

	return false
}

// SetBypassCode gets a reference to the given string and assigns it to the BypassCode field.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) SetBypassCode(v string) {
	o.BypassCode = &v
}

// GetDeviceTrustToken returns the DeviceTrustToken field value if set, zero value otherwise.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetDeviceTrustToken() string {
	if o == nil || IsNil(o.DeviceTrustToken) {
		var ret string
		return ret
	}
	return *o.DeviceTrustToken
}

// GetDeviceTrustTokenOk returns a tuple with the DeviceTrustToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetDeviceTrustTokenOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceTrustToken) {
		return nil, false
	}
	return o.DeviceTrustToken, true
}

// HasDeviceTrustToken returns a boolean if a field has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) HasDeviceTrustToken() bool {
	if o != nil && !IsNil(o.DeviceTrustToken) {
		return true
	}

	return false
}

// SetDeviceTrustToken gets a reference to the given string and assigns it to the DeviceTrustToken field.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) SetDeviceTrustToken(v string) {
	o.DeviceTrustToken = &v
}

// GetEmail returns the Email field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) SetEmail(v string) {
	o.Email = v
}

// GetIp returns the Ip field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) SetIp(v string) {
	o.Ip = v
}

// GetPassword returns the Password field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) SetPassword(v string) {
	o.Password = v
}

// GetUserAgent returns the UserAgent field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetUserAgent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value
// and a boolean to check if the value has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) GetUserAgentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserAgent, true
}

// SetUserAgent sets field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) SetUserAgent(v string) {
	o.UserAgent = v
}

func (o GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BypassCode) {
		toSerialize["bypass_code"] = o.BypassCode
	}
	if !IsNil(o.DeviceTrustToken) {
		toSerialize["device_trust_token"] = o.DeviceTrustToken
	}
	toSerialize["email"] = o.Email
	toSerialize["ip"] = o.Ip
	toSerialize["password"] = o.Password
	toSerialize["user_agent"] = o.UserAgent
	return toSerialize, nil
}

func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"ip",
		"password",
		"user_agent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput := _GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput)

	if err != nil {
		return err
	}

	*o = GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput(varGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput)

	return err
}

type NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput struct {
	value *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput
	isSet bool
}

func (v NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) Get() *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput {
	return v.value
}

func (v *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) Set(val *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput(val *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput {
	return &NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput{value: val, isSet: true}
}

func (v NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


