/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SessionspbCreateSessionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionspbCreateSessionResponse{}

// SessionspbCreateSessionResponse struct for SessionspbCreateSessionResponse
type SessionspbCreateSessionResponse struct {
	// Types that are valid to be assigned to Payload:   *CreateSessionResponse_SessionCreated  *CreateSessionResponse_UserInBlacklist  *CreateSessionResponse_BadBypassCode  *CreateSessionResponse_LoginFromNewDevice
	Payload map[string]interface{} `json:"payload,omitempty"`
}

// NewSessionspbCreateSessionResponse instantiates a new SessionspbCreateSessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionspbCreateSessionResponse() *SessionspbCreateSessionResponse {
	this := SessionspbCreateSessionResponse{}
	return &this
}

// NewSessionspbCreateSessionResponseWithDefaults instantiates a new SessionspbCreateSessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionspbCreateSessionResponseWithDefaults() *SessionspbCreateSessionResponse {
	this := SessionspbCreateSessionResponse{}
	return &this
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *SessionspbCreateSessionResponse) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionspbCreateSessionResponse) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *SessionspbCreateSessionResponse) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *SessionspbCreateSessionResponse) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

func (o SessionspbCreateSessionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionspbCreateSessionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

type NullableSessionspbCreateSessionResponse struct {
	value *SessionspbCreateSessionResponse
	isSet bool
}

func (v NullableSessionspbCreateSessionResponse) Get() *SessionspbCreateSessionResponse {
	return v.value
}

func (v *NullableSessionspbCreateSessionResponse) Set(val *SessionspbCreateSessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionspbCreateSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionspbCreateSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionspbCreateSessionResponse(val *SessionspbCreateSessionResponse) *NullableSessionspbCreateSessionResponse {
	return &NullableSessionspbCreateSessionResponse{value: val, isSet: true}
}

func (v NullableSessionspbCreateSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionspbCreateSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


