/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TimestamppbTimestamp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimestamppbTimestamp{}

// TimestamppbTimestamp struct for TimestamppbTimestamp
type TimestamppbTimestamp struct {
	// Non-negative fractions of a second at nanosecond resolution. This field is the nanosecond portion of the duration, not an alternative to seconds. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be between 0 and 999,999,999 inclusive.
	Nanos *int32 `json:"nanos,omitempty"`
	// Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be between -315576000000 and 315576000000 inclusive (which corresponds to 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z).
	Seconds *int32 `json:"seconds,omitempty"`
}

// NewTimestamppbTimestamp instantiates a new TimestamppbTimestamp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimestamppbTimestamp() *TimestamppbTimestamp {
	this := TimestamppbTimestamp{}
	return &this
}

// NewTimestamppbTimestampWithDefaults instantiates a new TimestamppbTimestamp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimestamppbTimestampWithDefaults() *TimestamppbTimestamp {
	this := TimestamppbTimestamp{}
	return &this
}

// GetNanos returns the Nanos field value if set, zero value otherwise.
func (o *TimestamppbTimestamp) GetNanos() int32 {
	if o == nil || IsNil(o.Nanos) {
		var ret int32
		return ret
	}
	return *o.Nanos
}

// GetNanosOk returns a tuple with the Nanos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimestamppbTimestamp) GetNanosOk() (*int32, bool) {
	if o == nil || IsNil(o.Nanos) {
		return nil, false
	}
	return o.Nanos, true
}

// HasNanos returns a boolean if a field has been set.
func (o *TimestamppbTimestamp) HasNanos() bool {
	if o != nil && !IsNil(o.Nanos) {
		return true
	}

	return false
}

// SetNanos gets a reference to the given int32 and assigns it to the Nanos field.
func (o *TimestamppbTimestamp) SetNanos(v int32) {
	o.Nanos = &v
}

// GetSeconds returns the Seconds field value if set, zero value otherwise.
func (o *TimestamppbTimestamp) GetSeconds() int32 {
	if o == nil || IsNil(o.Seconds) {
		var ret int32
		return ret
	}
	return *o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimestamppbTimestamp) GetSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.Seconds) {
		return nil, false
	}
	return o.Seconds, true
}

// HasSeconds returns a boolean if a field has been set.
func (o *TimestamppbTimestamp) HasSeconds() bool {
	if o != nil && !IsNil(o.Seconds) {
		return true
	}

	return false
}

// SetSeconds gets a reference to the given int32 and assigns it to the Seconds field.
func (o *TimestamppbTimestamp) SetSeconds(v int32) {
	o.Seconds = &v
}

func (o TimestamppbTimestamp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimestamppbTimestamp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nanos) {
		toSerialize["nanos"] = o.Nanos
	}
	if !IsNil(o.Seconds) {
		toSerialize["seconds"] = o.Seconds
	}
	return toSerialize, nil
}

type NullableTimestamppbTimestamp struct {
	value *TimestamppbTimestamp
	isSet bool
}

func (v NullableTimestamppbTimestamp) Get() *TimestamppbTimestamp {
	return v.value
}

func (v *NullableTimestamppbTimestamp) Set(val *TimestamppbTimestamp) {
	v.value = val
	v.isSet = true
}

func (v NullableTimestamppbTimestamp) IsSet() bool {
	return v.isSet
}

func (v *NullableTimestamppbTimestamp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimestamppbTimestamp(val *TimestamppbTimestamp) *NullableTimestamppbTimestamp {
	return &NullableTimestamppbTimestamp{value: val, isSet: true}
}

func (v NullableTimestamppbTimestamp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimestamppbTimestamp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


