/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserspbCreateUserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserspbCreateUserRequest{}

// UserspbCreateUserRequest struct for UserspbCreateUserRequest
type UserspbCreateUserRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
}

type _UserspbCreateUserRequest UserspbCreateUserRequest

// NewUserspbCreateUserRequest instantiates a new UserspbCreateUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserspbCreateUserRequest(email string, password string) *UserspbCreateUserRequest {
	this := UserspbCreateUserRequest{}
	this.Email = email
	this.Password = password
	return &this
}

// NewUserspbCreateUserRequestWithDefaults instantiates a new UserspbCreateUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserspbCreateUserRequestWithDefaults() *UserspbCreateUserRequest {
	this := UserspbCreateUserRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *UserspbCreateUserRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserspbCreateUserRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserspbCreateUserRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *UserspbCreateUserRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UserspbCreateUserRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UserspbCreateUserRequest) SetPassword(v string) {
	o.Password = v
}

func (o UserspbCreateUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserspbCreateUserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *UserspbCreateUserRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserspbCreateUserRequest := _UserspbCreateUserRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserspbCreateUserRequest)

	if err != nil {
		return err
	}

	*o = UserspbCreateUserRequest(varUserspbCreateUserRequest)

	return err
}

type NullableUserspbCreateUserRequest struct {
	value *UserspbCreateUserRequest
	isSet bool
}

func (v NullableUserspbCreateUserRequest) Get() *UserspbCreateUserRequest {
	return v.value
}

func (v *NullableUserspbCreateUserRequest) Set(val *UserspbCreateUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserspbCreateUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserspbCreateUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserspbCreateUserRequest(val *UserspbCreateUserRequest) *NullableUserspbCreateUserRequest {
	return &NullableUserspbCreateUserRequest{value: val, isSet: true}
}

func (v NullableUserspbCreateUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserspbCreateUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


