/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserspbProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserspbProfile{}

// UserspbProfile struct for UserspbProfile
type UserspbProfile struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	BirthDate *string `json:"birth_date,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	// GENDER_UNSPECIFIED = 0 Reserved for Proto, not a valid value GENDER_UNSELECTED = 1 User has not selected a gender GENDER_MALE = 2 Represents male gender GENDER_FEMALE = 3 Represents female gender
	Gender UserspbGenderValue `json:"gender"`
	LastName *string `json:"last_name,omitempty"`
	MiddleName *string `json:"middle_name,omitempty"`
	UpdatedAt TimestamppbTimestamp `json:"updated_at"`
}

type _UserspbProfile UserspbProfile

// NewUserspbProfile instantiates a new UserspbProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserspbProfile(gender UserspbGenderValue, updatedAt TimestamppbTimestamp) *UserspbProfile {
	this := UserspbProfile{}
	this.Gender = gender
	this.UpdatedAt = updatedAt
	return &this
}

// NewUserspbProfileWithDefaults instantiates a new UserspbProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserspbProfileWithDefaults() *UserspbProfile {
	this := UserspbProfile{}
	return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *UserspbProfile) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbProfile) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *UserspbProfile) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *UserspbProfile) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetBirthDate returns the BirthDate field value if set, zero value otherwise.
func (o *UserspbProfile) GetBirthDate() string {
	if o == nil || IsNil(o.BirthDate) {
		var ret string
		return ret
	}
	return *o.BirthDate
}

// GetBirthDateOk returns a tuple with the BirthDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbProfile) GetBirthDateOk() (*string, bool) {
	if o == nil || IsNil(o.BirthDate) {
		return nil, false
	}
	return o.BirthDate, true
}

// HasBirthDate returns a boolean if a field has been set.
func (o *UserspbProfile) HasBirthDate() bool {
	if o != nil && !IsNil(o.BirthDate) {
		return true
	}

	return false
}

// SetBirthDate gets a reference to the given string and assigns it to the BirthDate field.
func (o *UserspbProfile) SetBirthDate(v string) {
	o.BirthDate = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserspbProfile) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbProfile) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserspbProfile) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserspbProfile) SetFirstName(v string) {
	o.FirstName = &v
}

// GetGender returns the Gender field value
func (o *UserspbProfile) GetGender() UserspbGenderValue {
	if o == nil {
		var ret UserspbGenderValue
		return ret
	}

	return o.Gender
}

// GetGenderOk returns a tuple with the Gender field value
// and a boolean to check if the value has been set.
func (o *UserspbProfile) GetGenderOk() (*UserspbGenderValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gender, true
}

// SetGender sets field value
func (o *UserspbProfile) SetGender(v UserspbGenderValue) {
	o.Gender = v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserspbProfile) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbProfile) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserspbProfile) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserspbProfile) SetLastName(v string) {
	o.LastName = &v
}

// GetMiddleName returns the MiddleName field value if set, zero value otherwise.
func (o *UserspbProfile) GetMiddleName() string {
	if o == nil || IsNil(o.MiddleName) {
		var ret string
		return ret
	}
	return *o.MiddleName
}

// GetMiddleNameOk returns a tuple with the MiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbProfile) GetMiddleNameOk() (*string, bool) {
	if o == nil || IsNil(o.MiddleName) {
		return nil, false
	}
	return o.MiddleName, true
}

// HasMiddleName returns a boolean if a field has been set.
func (o *UserspbProfile) HasMiddleName() bool {
	if o != nil && !IsNil(o.MiddleName) {
		return true
	}

	return false
}

// SetMiddleName gets a reference to the given string and assigns it to the MiddleName field.
func (o *UserspbProfile) SetMiddleName(v string) {
	o.MiddleName = &v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UserspbProfile) GetUpdatedAt() TimestamppbTimestamp {
	if o == nil {
		var ret TimestamppbTimestamp
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UserspbProfile) GetUpdatedAtOk() (*TimestamppbTimestamp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UserspbProfile) SetUpdatedAt(v TimestamppbTimestamp) {
	o.UpdatedAt = v
}

func (o UserspbProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserspbProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	if !IsNil(o.BirthDate) {
		toSerialize["birth_date"] = o.BirthDate
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	toSerialize["gender"] = o.Gender
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.MiddleName) {
		toSerialize["middle_name"] = o.MiddleName
	}
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *UserspbProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"gender",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserspbProfile := _UserspbProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserspbProfile)

	if err != nil {
		return err
	}

	*o = UserspbProfile(varUserspbProfile)

	return err
}

type NullableUserspbProfile struct {
	value *UserspbProfile
	isSet bool
}

func (v NullableUserspbProfile) Get() *UserspbProfile {
	return v.value
}

func (v *NullableUserspbProfile) Set(val *UserspbProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableUserspbProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableUserspbProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserspbProfile(val *UserspbProfile) *NullableUserspbProfile {
	return &NullableUserspbProfile{value: val, isSet: true}
}

func (v NullableUserspbProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserspbProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


