/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ErrdetailsBadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrdetailsBadRequest{}

// ErrdetailsBadRequest struct for ErrdetailsBadRequest
type ErrdetailsBadRequest struct {
	// Describes all violations in a client request.
	FieldViolations []ErrdetailsBadRequestFieldViolation `json:"field_violations,omitempty"`
}

// NewErrdetailsBadRequest instantiates a new ErrdetailsBadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrdetailsBadRequest() *ErrdetailsBadRequest {
	this := ErrdetailsBadRequest{}
	return &this
}

// NewErrdetailsBadRequestWithDefaults instantiates a new ErrdetailsBadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrdetailsBadRequestWithDefaults() *ErrdetailsBadRequest {
	this := ErrdetailsBadRequest{}
	return &this
}

// GetFieldViolations returns the FieldViolations field value if set, zero value otherwise.
func (o *ErrdetailsBadRequest) GetFieldViolations() []ErrdetailsBadRequestFieldViolation {
	if o == nil || IsNil(o.FieldViolations) {
		var ret []ErrdetailsBadRequestFieldViolation
		return ret
	}
	return o.FieldViolations
}

// GetFieldViolationsOk returns a tuple with the FieldViolations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrdetailsBadRequest) GetFieldViolationsOk() ([]ErrdetailsBadRequestFieldViolation, bool) {
	if o == nil || IsNil(o.FieldViolations) {
		return nil, false
	}
	return o.FieldViolations, true
}

// HasFieldViolations returns a boolean if a field has been set.
func (o *ErrdetailsBadRequest) HasFieldViolations() bool {
	if o != nil && !IsNil(o.FieldViolations) {
		return true
	}

	return false
}

// SetFieldViolations gets a reference to the given []ErrdetailsBadRequestFieldViolation and assigns it to the FieldViolations field.
func (o *ErrdetailsBadRequest) SetFieldViolations(v []ErrdetailsBadRequestFieldViolation) {
	o.FieldViolations = v
}

func (o ErrdetailsBadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrdetailsBadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FieldViolations) {
		toSerialize["field_violations"] = o.FieldViolations
	}
	return toSerialize, nil
}

type NullableErrdetailsBadRequest struct {
	value *ErrdetailsBadRequest
	isSet bool
}

func (v NullableErrdetailsBadRequest) Get() *ErrdetailsBadRequest {
	return v.value
}

func (v *NullableErrdetailsBadRequest) Set(val *ErrdetailsBadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableErrdetailsBadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableErrdetailsBadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrdetailsBadRequest(val *ErrdetailsBadRequest) *NullableErrdetailsBadRequest {
	return &NullableErrdetailsBadRequest{value: val, isSet: true}
}

func (v NullableErrdetailsBadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrdetailsBadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


