/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserspbUserSessionActionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserspbUserSessionActionResponse{}

// UserspbUserSessionActionResponse struct for UserspbUserSessionActionResponse
type UserspbUserSessionActionResponse struct {
	// Types that are valid to be assigned to Payload:   *UserSessionActionResponse_Deleted  *UserSessionActionResponse_EmailNotVerified  *UserSessionActionResponse_BadCredentials  *UserSessionActionResponse_Ok
	Payload map[string]interface{} `json:"payload,omitempty"`
}

// NewUserspbUserSessionActionResponse instantiates a new UserspbUserSessionActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserspbUserSessionActionResponse() *UserspbUserSessionActionResponse {
	this := UserspbUserSessionActionResponse{}
	return &this
}

// NewUserspbUserSessionActionResponseWithDefaults instantiates a new UserspbUserSessionActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserspbUserSessionActionResponseWithDefaults() *UserspbUserSessionActionResponse {
	this := UserspbUserSessionActionResponse{}
	return &this
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *UserspbUserSessionActionResponse) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbUserSessionActionResponse) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *UserspbUserSessionActionResponse) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *UserspbUserSessionActionResponse) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

func (o UserspbUserSessionActionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserspbUserSessionActionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

type NullableUserspbUserSessionActionResponse struct {
	value *UserspbUserSessionActionResponse
	isSet bool
}

func (v NullableUserspbUserSessionActionResponse) Get() *UserspbUserSessionActionResponse {
	return v.value
}

func (v *NullableUserspbUserSessionActionResponse) Set(val *UserspbUserSessionActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserspbUserSessionActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserspbUserSessionActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserspbUserSessionActionResponse(val *UserspbUserSessionActionResponse) *NullableUserspbUserSessionActionResponse {
	return &NullableUserspbUserSessionActionResponse{value: val, isSet: true}
}

func (v NullableUserspbUserSessionActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserspbUserSessionActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


