/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"fmt"
)

// GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType the model 'GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType'
type GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType int32

// List of github_com_fedotovmax_microservices-shop_api-gateway_internal_domain.LoginErrorResponseType
const (
	LoginErrorResponseTypeUserDeleted GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType = 0
	LoginErrorResponseTypeBadCredentials GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType = 1
	LoginErrorResponseTypeEmailNotVerified GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType = 2
	LoginErrorResponseTypeBadBypassCode GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType = 3
	LoginErrorResponseTypeLoginFromNewDevice GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType = 4
	LoginErrorResponseTypeUserInBlacklist GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType = 5
)

// All allowed values of GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType enum
var AllowedGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseTypeEnumValues = []GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType{
	0,
	1,
	2,
	3,
	4,
	5,
}

func (v *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType(value)
	for _, existing := range AllowedGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType", value)
}

// NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseTypeFromValue returns a pointer to a valid GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseTypeFromValue(v int32) (*GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType, error) {
	ev := GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType: valid values are %v", v, AllowedGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) IsValid() bool {
	for _, existing := range AllowedGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to github_com_fedotovmax_microservices-shop_api-gateway_internal_domain.LoginErrorResponseType value
func (v GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) Ptr() *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType {
	return &v
}

type NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType struct {
	value *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType
	isSet bool
}

func (v NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) Get() *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType {
	return v.value
}

func (v *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) Set(val *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType(val *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType {
	return &NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType{value: val, isSet: true}
}

func (v NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

