/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse{}

// GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse struct for GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse
type GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse struct {
	Message string `json:"message"`
	Type GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType `json:"type"`
}

type _GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse

// NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse instantiates a new GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse(message string, type_ GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse {
	this := GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse{}
	this.Message = message
	this.Type = type_
	return &this
}

// NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseWithDefaults instantiates a new GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseWithDefaults() *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse {
	this := GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) SetMessage(v string) {
	o.Message = v
}

// GetType returns the Type field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) GetType() GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType {
	if o == nil {
		var ret GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) GetTypeOk() (*GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) SetType(v GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponseType) {
	o.Type = v
}

func (o GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse := _GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse)

	if err != nil {
		return err
	}

	*o = GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse(varGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse)

	return err
}

type NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse struct {
	value *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse
	isSet bool
}

func (v NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) Get() *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse {
	return v.value
}

func (v *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) Set(val *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse(val *GithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse {
	return &NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse{value: val, isSet: true}
}

func (v NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComFedotovmaxMicroservicesShopApiGatewayInternalDomainLoginErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


