/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ErrdetailsLocalizedMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrdetailsLocalizedMessage{}

// ErrdetailsLocalizedMessage struct for ErrdetailsLocalizedMessage
type ErrdetailsLocalizedMessage struct {
	// The locale used following the specification defined at https://www.rfc-editor.org/rfc/bcp/bcp47.txt. Examples are: \"en-US\", \"fr-CH\", \"es-MX\"
	Locale *string `json:"locale,omitempty"`
	// The localized error message in the above locale.
	Message *string `json:"message,omitempty"`
}

// NewErrdetailsLocalizedMessage instantiates a new ErrdetailsLocalizedMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrdetailsLocalizedMessage() *ErrdetailsLocalizedMessage {
	this := ErrdetailsLocalizedMessage{}
	return &this
}

// NewErrdetailsLocalizedMessageWithDefaults instantiates a new ErrdetailsLocalizedMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrdetailsLocalizedMessageWithDefaults() *ErrdetailsLocalizedMessage {
	this := ErrdetailsLocalizedMessage{}
	return &this
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *ErrdetailsLocalizedMessage) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrdetailsLocalizedMessage) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *ErrdetailsLocalizedMessage) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *ErrdetailsLocalizedMessage) SetLocale(v string) {
	o.Locale = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ErrdetailsLocalizedMessage) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrdetailsLocalizedMessage) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ErrdetailsLocalizedMessage) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ErrdetailsLocalizedMessage) SetMessage(v string) {
	o.Message = &v
}

func (o ErrdetailsLocalizedMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrdetailsLocalizedMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableErrdetailsLocalizedMessage struct {
	value *ErrdetailsLocalizedMessage
	isSet bool
}

func (v NullableErrdetailsLocalizedMessage) Get() *ErrdetailsLocalizedMessage {
	return v.value
}

func (v *NullableErrdetailsLocalizedMessage) Set(val *ErrdetailsLocalizedMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableErrdetailsLocalizedMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableErrdetailsLocalizedMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrdetailsLocalizedMessage(val *ErrdetailsLocalizedMessage) *NullableErrdetailsLocalizedMessage {
	return &NullableErrdetailsLocalizedMessage{value: val, isSet: true}
}

func (v NullableErrdetailsLocalizedMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrdetailsLocalizedMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


