/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserspbUpdateUserProfileData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserspbUpdateUserProfileData{}

// UserspbUpdateUserProfileData struct for UserspbUpdateUserProfileData
type UserspbUpdateUserProfileData struct {
	AvatarUrl *string `json:"avatar_url,omitempty"`
	BirthDate *string `json:"birth_date,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	// GENDER_UNSPECIFIED = 0 Reserved for Proto, not a valid value GENDER_UNSELECTED = 1 User has not selected a gender GENDER_MALE = 2 Represents male gender GENDER_FEMALE = 3 Represents female gender
	GenderValue *UserspbGenderValue `json:"gender_value,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	MiddleName *string `json:"middle_name,omitempty"`
}

// NewUserspbUpdateUserProfileData instantiates a new UserspbUpdateUserProfileData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserspbUpdateUserProfileData() *UserspbUpdateUserProfileData {
	this := UserspbUpdateUserProfileData{}
	return &this
}

// NewUserspbUpdateUserProfileDataWithDefaults instantiates a new UserspbUpdateUserProfileData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserspbUpdateUserProfileDataWithDefaults() *UserspbUpdateUserProfileData {
	this := UserspbUpdateUserProfileData{}
	return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *UserspbUpdateUserProfileData) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbUpdateUserProfileData) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *UserspbUpdateUserProfileData) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *UserspbUpdateUserProfileData) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetBirthDate returns the BirthDate field value if set, zero value otherwise.
func (o *UserspbUpdateUserProfileData) GetBirthDate() string {
	if o == nil || IsNil(o.BirthDate) {
		var ret string
		return ret
	}
	return *o.BirthDate
}

// GetBirthDateOk returns a tuple with the BirthDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbUpdateUserProfileData) GetBirthDateOk() (*string, bool) {
	if o == nil || IsNil(o.BirthDate) {
		return nil, false
	}
	return o.BirthDate, true
}

// HasBirthDate returns a boolean if a field has been set.
func (o *UserspbUpdateUserProfileData) HasBirthDate() bool {
	if o != nil && !IsNil(o.BirthDate) {
		return true
	}

	return false
}

// SetBirthDate gets a reference to the given string and assigns it to the BirthDate field.
func (o *UserspbUpdateUserProfileData) SetBirthDate(v string) {
	o.BirthDate = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserspbUpdateUserProfileData) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbUpdateUserProfileData) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserspbUpdateUserProfileData) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserspbUpdateUserProfileData) SetFirstName(v string) {
	o.FirstName = &v
}

// GetGenderValue returns the GenderValue field value if set, zero value otherwise.
func (o *UserspbUpdateUserProfileData) GetGenderValue() UserspbGenderValue {
	if o == nil || IsNil(o.GenderValue) {
		var ret UserspbGenderValue
		return ret
	}
	return *o.GenderValue
}

// GetGenderValueOk returns a tuple with the GenderValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbUpdateUserProfileData) GetGenderValueOk() (*UserspbGenderValue, bool) {
	if o == nil || IsNil(o.GenderValue) {
		return nil, false
	}
	return o.GenderValue, true
}

// HasGenderValue returns a boolean if a field has been set.
func (o *UserspbUpdateUserProfileData) HasGenderValue() bool {
	if o != nil && !IsNil(o.GenderValue) {
		return true
	}

	return false
}

// SetGenderValue gets a reference to the given UserspbGenderValue and assigns it to the GenderValue field.
func (o *UserspbUpdateUserProfileData) SetGenderValue(v UserspbGenderValue) {
	o.GenderValue = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserspbUpdateUserProfileData) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbUpdateUserProfileData) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserspbUpdateUserProfileData) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserspbUpdateUserProfileData) SetLastName(v string) {
	o.LastName = &v
}

// GetMiddleName returns the MiddleName field value if set, zero value otherwise.
func (o *UserspbUpdateUserProfileData) GetMiddleName() string {
	if o == nil || IsNil(o.MiddleName) {
		var ret string
		return ret
	}
	return *o.MiddleName
}

// GetMiddleNameOk returns a tuple with the MiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbUpdateUserProfileData) GetMiddleNameOk() (*string, bool) {
	if o == nil || IsNil(o.MiddleName) {
		return nil, false
	}
	return o.MiddleName, true
}

// HasMiddleName returns a boolean if a field has been set.
func (o *UserspbUpdateUserProfileData) HasMiddleName() bool {
	if o != nil && !IsNil(o.MiddleName) {
		return true
	}

	return false
}

// SetMiddleName gets a reference to the given string and assigns it to the MiddleName field.
func (o *UserspbUpdateUserProfileData) SetMiddleName(v string) {
	o.MiddleName = &v
}

func (o UserspbUpdateUserProfileData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserspbUpdateUserProfileData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	if !IsNil(o.BirthDate) {
		toSerialize["birth_date"] = o.BirthDate
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.GenderValue) {
		toSerialize["gender_value"] = o.GenderValue
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.MiddleName) {
		toSerialize["middle_name"] = o.MiddleName
	}
	return toSerialize, nil
}

type NullableUserspbUpdateUserProfileData struct {
	value *UserspbUpdateUserProfileData
	isSet bool
}

func (v NullableUserspbUpdateUserProfileData) Get() *UserspbUpdateUserProfileData {
	return v.value
}

func (v *NullableUserspbUpdateUserProfileData) Set(val *UserspbUpdateUserProfileData) {
	v.value = val
	v.isSet = true
}

func (v NullableUserspbUpdateUserProfileData) IsSet() bool {
	return v.isSet
}

func (v *NullableUserspbUpdateUserProfileData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserspbUpdateUserProfileData(val *UserspbUpdateUserProfileData) *NullableUserspbUpdateUserProfileData {
	return &NullableUserspbUpdateUserProfileData{value: val, isSet: true}
}

func (v NullableUserspbUpdateUserProfileData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserspbUpdateUserProfileData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


