/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionspbRefreshSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionspbRefreshSessionRequest{}

// SessionspbRefreshSessionRequest struct for SessionspbRefreshSessionRequest
type SessionspbRefreshSessionRequest struct {
	Ip string `json:"ip"`
	RefreshToken string `json:"refresh_token"`
	UserAgent string `json:"user_agent"`
}

type _SessionspbRefreshSessionRequest SessionspbRefreshSessionRequest

// NewSessionspbRefreshSessionRequest instantiates a new SessionspbRefreshSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionspbRefreshSessionRequest(ip string, refreshToken string, userAgent string) *SessionspbRefreshSessionRequest {
	this := SessionspbRefreshSessionRequest{}
	this.Ip = ip
	this.RefreshToken = refreshToken
	this.UserAgent = userAgent
	return &this
}

// NewSessionspbRefreshSessionRequestWithDefaults instantiates a new SessionspbRefreshSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionspbRefreshSessionRequestWithDefaults() *SessionspbRefreshSessionRequest {
	this := SessionspbRefreshSessionRequest{}
	return &this
}

// GetIp returns the Ip field value
func (o *SessionspbRefreshSessionRequest) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *SessionspbRefreshSessionRequest) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *SessionspbRefreshSessionRequest) SetIp(v string) {
	o.Ip = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *SessionspbRefreshSessionRequest) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *SessionspbRefreshSessionRequest) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *SessionspbRefreshSessionRequest) SetRefreshToken(v string) {
	o.RefreshToken = v
}

// GetUserAgent returns the UserAgent field value
func (o *SessionspbRefreshSessionRequest) GetUserAgent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value
// and a boolean to check if the value has been set.
func (o *SessionspbRefreshSessionRequest) GetUserAgentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserAgent, true
}

// SetUserAgent sets field value
func (o *SessionspbRefreshSessionRequest) SetUserAgent(v string) {
	o.UserAgent = v
}

func (o SessionspbRefreshSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionspbRefreshSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ip"] = o.Ip
	toSerialize["refresh_token"] = o.RefreshToken
	toSerialize["user_agent"] = o.UserAgent
	return toSerialize, nil
}

func (o *SessionspbRefreshSessionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ip",
		"refresh_token",
		"user_agent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionspbRefreshSessionRequest := _SessionspbRefreshSessionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionspbRefreshSessionRequest)

	if err != nil {
		return err
	}

	*o = SessionspbRefreshSessionRequest(varSessionspbRefreshSessionRequest)

	return err
}

type NullableSessionspbRefreshSessionRequest struct {
	value *SessionspbRefreshSessionRequest
	isSet bool
}

func (v NullableSessionspbRefreshSessionRequest) Get() *SessionspbRefreshSessionRequest {
	return v.value
}

func (v *NullableSessionspbRefreshSessionRequest) Set(val *SessionspbRefreshSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionspbRefreshSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionspbRefreshSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionspbRefreshSessionRequest(val *SessionspbRefreshSessionRequest) *NullableSessionspbRefreshSessionRequest {
	return &NullableSessionspbRefreshSessionRequest{value: val, isSet: true}
}

func (v NullableSessionspbRefreshSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionspbRefreshSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


