/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionspbSessionCreated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionspbSessionCreated{}

// SessionspbSessionCreated struct for SessionspbSessionCreated
type SessionspbSessionCreated struct {
	AccessExpTime TimestamppbTimestamp `json:"access_exp_time"`
	AccessToken string `json:"access_token"`
	RefreshExpTime TimestamppbTimestamp `json:"refresh_exp_time"`
	RefreshToken string `json:"refresh_token"`
	TrustToken *SessionspbCreatedTrustToken `json:"trust_token,omitempty"`
}

type _SessionspbSessionCreated SessionspbSessionCreated

// NewSessionspbSessionCreated instantiates a new SessionspbSessionCreated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionspbSessionCreated(accessExpTime TimestamppbTimestamp, accessToken string, refreshExpTime TimestamppbTimestamp, refreshToken string) *SessionspbSessionCreated {
	this := SessionspbSessionCreated{}
	this.AccessExpTime = accessExpTime
	this.AccessToken = accessToken
	this.RefreshExpTime = refreshExpTime
	this.RefreshToken = refreshToken
	return &this
}

// NewSessionspbSessionCreatedWithDefaults instantiates a new SessionspbSessionCreated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionspbSessionCreatedWithDefaults() *SessionspbSessionCreated {
	this := SessionspbSessionCreated{}
	return &this
}

// GetAccessExpTime returns the AccessExpTime field value
func (o *SessionspbSessionCreated) GetAccessExpTime() TimestamppbTimestamp {
	if o == nil {
		var ret TimestamppbTimestamp
		return ret
	}

	return o.AccessExpTime
}

// GetAccessExpTimeOk returns a tuple with the AccessExpTime field value
// and a boolean to check if the value has been set.
func (o *SessionspbSessionCreated) GetAccessExpTimeOk() (*TimestamppbTimestamp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessExpTime, true
}

// SetAccessExpTime sets field value
func (o *SessionspbSessionCreated) SetAccessExpTime(v TimestamppbTimestamp) {
	o.AccessExpTime = v
}

// GetAccessToken returns the AccessToken field value
func (o *SessionspbSessionCreated) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *SessionspbSessionCreated) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *SessionspbSessionCreated) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetRefreshExpTime returns the RefreshExpTime field value
func (o *SessionspbSessionCreated) GetRefreshExpTime() TimestamppbTimestamp {
	if o == nil {
		var ret TimestamppbTimestamp
		return ret
	}

	return o.RefreshExpTime
}

// GetRefreshExpTimeOk returns a tuple with the RefreshExpTime field value
// and a boolean to check if the value has been set.
func (o *SessionspbSessionCreated) GetRefreshExpTimeOk() (*TimestamppbTimestamp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshExpTime, true
}

// SetRefreshExpTime sets field value
func (o *SessionspbSessionCreated) SetRefreshExpTime(v TimestamppbTimestamp) {
	o.RefreshExpTime = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *SessionspbSessionCreated) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *SessionspbSessionCreated) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *SessionspbSessionCreated) SetRefreshToken(v string) {
	o.RefreshToken = v
}

// GetTrustToken returns the TrustToken field value if set, zero value otherwise.
func (o *SessionspbSessionCreated) GetTrustToken() SessionspbCreatedTrustToken {
	if o == nil || IsNil(o.TrustToken) {
		var ret SessionspbCreatedTrustToken
		return ret
	}
	return *o.TrustToken
}

// GetTrustTokenOk returns a tuple with the TrustToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionspbSessionCreated) GetTrustTokenOk() (*SessionspbCreatedTrustToken, bool) {
	if o == nil || IsNil(o.TrustToken) {
		return nil, false
	}
	return o.TrustToken, true
}

// HasTrustToken returns a boolean if a field has been set.
func (o *SessionspbSessionCreated) HasTrustToken() bool {
	if o != nil && !IsNil(o.TrustToken) {
		return true
	}

	return false
}

// SetTrustToken gets a reference to the given SessionspbCreatedTrustToken and assigns it to the TrustToken field.
func (o *SessionspbSessionCreated) SetTrustToken(v SessionspbCreatedTrustToken) {
	o.TrustToken = &v
}

func (o SessionspbSessionCreated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionspbSessionCreated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_exp_time"] = o.AccessExpTime
	toSerialize["access_token"] = o.AccessToken
	toSerialize["refresh_exp_time"] = o.RefreshExpTime
	toSerialize["refresh_token"] = o.RefreshToken
	if !IsNil(o.TrustToken) {
		toSerialize["trust_token"] = o.TrustToken
	}
	return toSerialize, nil
}

func (o *SessionspbSessionCreated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_exp_time",
		"access_token",
		"refresh_exp_time",
		"refresh_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionspbSessionCreated := _SessionspbSessionCreated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionspbSessionCreated)

	if err != nil {
		return err
	}

	*o = SessionspbSessionCreated(varSessionspbSessionCreated)

	return err
}

type NullableSessionspbSessionCreated struct {
	value *SessionspbSessionCreated
	isSet bool
}

func (v NullableSessionspbSessionCreated) Get() *SessionspbSessionCreated {
	return v.value
}

func (v *NullableSessionspbSessionCreated) Set(val *SessionspbSessionCreated) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionspbSessionCreated) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionspbSessionCreated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionspbSessionCreated(val *SessionspbSessionCreated) *NullableSessionspbSessionCreated {
	return &NullableSessionspbSessionCreated{value: val, isSet: true}
}

func (v NullableSessionspbSessionCreated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionspbSessionCreated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


