/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HttputilsErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttputilsErrorResponse{}

// HttputilsErrorResponse struct for HttputilsErrorResponse
type HttputilsErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// NewHttputilsErrorResponse instantiates a new HttputilsErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttputilsErrorResponse() *HttputilsErrorResponse {
	this := HttputilsErrorResponse{}
	return &this
}

// NewHttputilsErrorResponseWithDefaults instantiates a new HttputilsErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttputilsErrorResponseWithDefaults() *HttputilsErrorResponse {
	this := HttputilsErrorResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *HttputilsErrorResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttputilsErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *HttputilsErrorResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *HttputilsErrorResponse) SetMessage(v string) {
	o.Message = &v
}

func (o HttputilsErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttputilsErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableHttputilsErrorResponse struct {
	value *HttputilsErrorResponse
	isSet bool
}

func (v NullableHttputilsErrorResponse) Get() *HttputilsErrorResponse {
	return v.value
}

func (v *NullableHttputilsErrorResponse) Set(val *HttputilsErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHttputilsErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHttputilsErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttputilsErrorResponse(val *HttputilsErrorResponse) *NullableHttputilsErrorResponse {
	return &NullableHttputilsErrorResponse{value: val, isSet: true}
}

func (v NullableHttputilsErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttputilsErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


