/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionspbCreatedTrustToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionspbCreatedTrustToken{}

// SessionspbCreatedTrustToken struct for SessionspbCreatedTrustToken
type SessionspbCreatedTrustToken struct {
	TrustTokenExpTime *TimestamppbTimestamp `json:"trust_token_exp_time,omitempty"`
	TrustTokenValue string `json:"trust_token_value"`
}

type _SessionspbCreatedTrustToken SessionspbCreatedTrustToken

// NewSessionspbCreatedTrustToken instantiates a new SessionspbCreatedTrustToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionspbCreatedTrustToken(trustTokenValue string) *SessionspbCreatedTrustToken {
	this := SessionspbCreatedTrustToken{}
	this.TrustTokenValue = trustTokenValue
	return &this
}

// NewSessionspbCreatedTrustTokenWithDefaults instantiates a new SessionspbCreatedTrustToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionspbCreatedTrustTokenWithDefaults() *SessionspbCreatedTrustToken {
	this := SessionspbCreatedTrustToken{}
	return &this
}

// GetTrustTokenExpTime returns the TrustTokenExpTime field value if set, zero value otherwise.
func (o *SessionspbCreatedTrustToken) GetTrustTokenExpTime() TimestamppbTimestamp {
	if o == nil || IsNil(o.TrustTokenExpTime) {
		var ret TimestamppbTimestamp
		return ret
	}
	return *o.TrustTokenExpTime
}

// GetTrustTokenExpTimeOk returns a tuple with the TrustTokenExpTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionspbCreatedTrustToken) GetTrustTokenExpTimeOk() (*TimestamppbTimestamp, bool) {
	if o == nil || IsNil(o.TrustTokenExpTime) {
		return nil, false
	}
	return o.TrustTokenExpTime, true
}

// HasTrustTokenExpTime returns a boolean if a field has been set.
func (o *SessionspbCreatedTrustToken) HasTrustTokenExpTime() bool {
	if o != nil && !IsNil(o.TrustTokenExpTime) {
		return true
	}

	return false
}

// SetTrustTokenExpTime gets a reference to the given TimestamppbTimestamp and assigns it to the TrustTokenExpTime field.
func (o *SessionspbCreatedTrustToken) SetTrustTokenExpTime(v TimestamppbTimestamp) {
	o.TrustTokenExpTime = &v
}

// GetTrustTokenValue returns the TrustTokenValue field value
func (o *SessionspbCreatedTrustToken) GetTrustTokenValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrustTokenValue
}

// GetTrustTokenValueOk returns a tuple with the TrustTokenValue field value
// and a boolean to check if the value has been set.
func (o *SessionspbCreatedTrustToken) GetTrustTokenValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrustTokenValue, true
}

// SetTrustTokenValue sets field value
func (o *SessionspbCreatedTrustToken) SetTrustTokenValue(v string) {
	o.TrustTokenValue = v
}

func (o SessionspbCreatedTrustToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionspbCreatedTrustToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TrustTokenExpTime) {
		toSerialize["trust_token_exp_time"] = o.TrustTokenExpTime
	}
	toSerialize["trust_token_value"] = o.TrustTokenValue
	return toSerialize, nil
}

func (o *SessionspbCreatedTrustToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trust_token_value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionspbCreatedTrustToken := _SessionspbCreatedTrustToken{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionspbCreatedTrustToken)

	if err != nil {
		return err
	}

	*o = SessionspbCreatedTrustToken(varSessionspbCreatedTrustToken)

	return err
}

type NullableSessionspbCreatedTrustToken struct {
	value *SessionspbCreatedTrustToken
	isSet bool
}

func (v NullableSessionspbCreatedTrustToken) Get() *SessionspbCreatedTrustToken {
	return v.value
}

func (v *NullableSessionspbCreatedTrustToken) Set(val *SessionspbCreatedTrustToken) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionspbCreatedTrustToken) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionspbCreatedTrustToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionspbCreatedTrustToken(val *SessionspbCreatedTrustToken) *NullableSessionspbCreatedTrustToken {
	return &NullableSessionspbCreatedTrustToken{value: val, isSet: true}
}

func (v NullableSessionspbCreatedTrustToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionspbCreatedTrustToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


