/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// checks if the ErrdetailsBadRequestFieldViolation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrdetailsBadRequestFieldViolation{}

// ErrdetailsBadRequestFieldViolation struct for ErrdetailsBadRequestFieldViolation
type ErrdetailsBadRequestFieldViolation struct {
	// A description of why the request element is bad.
	Description *string `json:"description,omitempty"`
	// A path that leads to a field in the request body. The value will be a sequence of dot-separated identifiers that identify a protocol buffer field.  Consider the following:   message CreateContactRequest {    message EmailAddress {      enum Type {        TYPE_UNSPECIFIED = 0;        HOME = 1;        WORK = 2;      }       optional string email = 1;      repeated EmailType type = 2;    }     string full_name = 1;    repeated EmailAddress email_addresses = 2;  }  In this example, in proto `field` could take one of the following values:    - `full_name` for a violation in the `full_name` value   - `email_addresses[1].email` for a violation in the `email` field of the     first `email_addresses` message   - `email_addresses[3].type[2]` for a violation in the second `type`     value in the third `email_addresses` message.  In JSON, the same values are represented as:    - `fullName` for a violation in the `fullName` value   - `emailAddresses[1].email` for a violation in the `email` field of the     first `emailAddresses` message   - `emailAddresses[3].type[2]` for a violation in the second `type`     value in the third `emailAddresses` message.
	Field *string `json:"field,omitempty"`
	// Provides a localized error message for field-level errors that is safe to return to the API consumer.
	LocalizedMessage *ErrdetailsLocalizedMessage `json:"localized_message,omitempty"`
	// The reason of the field-level error. This is a constant value that identifies the proximate cause of the field-level error. It should uniquely identify the type of the FieldViolation within the scope of the google.rpc.ErrorInfo.domain. This should be at most 63 characters and match a regular expression of `[A-Z][A-Z0-9_]+[A-Z0-9]`, which represents UPPER_SNAKE_CASE.
	Reason *string `json:"reason,omitempty"`
}

// NewErrdetailsBadRequestFieldViolation instantiates a new ErrdetailsBadRequestFieldViolation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrdetailsBadRequestFieldViolation() *ErrdetailsBadRequestFieldViolation {
	this := ErrdetailsBadRequestFieldViolation{}
	return &this
}

// NewErrdetailsBadRequestFieldViolationWithDefaults instantiates a new ErrdetailsBadRequestFieldViolation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrdetailsBadRequestFieldViolationWithDefaults() *ErrdetailsBadRequestFieldViolation {
	this := ErrdetailsBadRequestFieldViolation{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ErrdetailsBadRequestFieldViolation) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrdetailsBadRequestFieldViolation) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ErrdetailsBadRequestFieldViolation) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ErrdetailsBadRequestFieldViolation) SetDescription(v string) {
	o.Description = &v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *ErrdetailsBadRequestFieldViolation) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrdetailsBadRequestFieldViolation) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *ErrdetailsBadRequestFieldViolation) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *ErrdetailsBadRequestFieldViolation) SetField(v string) {
	o.Field = &v
}

// GetLocalizedMessage returns the LocalizedMessage field value if set, zero value otherwise.
func (o *ErrdetailsBadRequestFieldViolation) GetLocalizedMessage() ErrdetailsLocalizedMessage {
	if o == nil || IsNil(o.LocalizedMessage) {
		var ret ErrdetailsLocalizedMessage
		return ret
	}
	return *o.LocalizedMessage
}

// GetLocalizedMessageOk returns a tuple with the LocalizedMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrdetailsBadRequestFieldViolation) GetLocalizedMessageOk() (*ErrdetailsLocalizedMessage, bool) {
	if o == nil || IsNil(o.LocalizedMessage) {
		return nil, false
	}
	return o.LocalizedMessage, true
}

// HasLocalizedMessage returns a boolean if a field has been set.
func (o *ErrdetailsBadRequestFieldViolation) HasLocalizedMessage() bool {
	if o != nil && !IsNil(o.LocalizedMessage) {
		return true
	}

	return false
}

// SetLocalizedMessage gets a reference to the given ErrdetailsLocalizedMessage and assigns it to the LocalizedMessage field.
func (o *ErrdetailsBadRequestFieldViolation) SetLocalizedMessage(v ErrdetailsLocalizedMessage) {
	o.LocalizedMessage = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *ErrdetailsBadRequestFieldViolation) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrdetailsBadRequestFieldViolation) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *ErrdetailsBadRequestFieldViolation) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *ErrdetailsBadRequestFieldViolation) SetReason(v string) {
	o.Reason = &v
}

func (o ErrdetailsBadRequestFieldViolation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrdetailsBadRequestFieldViolation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.LocalizedMessage) {
		toSerialize["localized_message"] = o.LocalizedMessage
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableErrdetailsBadRequestFieldViolation struct {
	value *ErrdetailsBadRequestFieldViolation
	isSet bool
}

func (v NullableErrdetailsBadRequestFieldViolation) Get() *ErrdetailsBadRequestFieldViolation {
	return v.value
}

func (v *NullableErrdetailsBadRequestFieldViolation) Set(val *ErrdetailsBadRequestFieldViolation) {
	v.value = val
	v.isSet = true
}

func (v NullableErrdetailsBadRequestFieldViolation) IsSet() bool {
	return v.isSet
}

func (v *NullableErrdetailsBadRequestFieldViolation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrdetailsBadRequestFieldViolation(val *ErrdetailsBadRequestFieldViolation) *NullableErrdetailsBadRequestFieldViolation {
	return &NullableErrdetailsBadRequestFieldViolation{value: val, isSet: true}
}

func (v NullableErrdetailsBadRequestFieldViolation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrdetailsBadRequestFieldViolation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


