/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserspbCreateUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserspbCreateUserResponse{}

// UserspbCreateUserResponse struct for UserspbCreateUserResponse
type UserspbCreateUserResponse struct {
	Id string `json:"id"`
}

type _UserspbCreateUserResponse UserspbCreateUserResponse

// NewUserspbCreateUserResponse instantiates a new UserspbCreateUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserspbCreateUserResponse(id string) *UserspbCreateUserResponse {
	this := UserspbCreateUserResponse{}
	this.Id = id
	return &this
}

// NewUserspbCreateUserResponseWithDefaults instantiates a new UserspbCreateUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserspbCreateUserResponseWithDefaults() *UserspbCreateUserResponse {
	this := UserspbCreateUserResponse{}
	return &this
}

// GetId returns the Id field value
func (o *UserspbCreateUserResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserspbCreateUserResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserspbCreateUserResponse) SetId(v string) {
	o.Id = v
}

func (o UserspbCreateUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserspbCreateUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *UserspbCreateUserResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserspbCreateUserResponse := _UserspbCreateUserResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserspbCreateUserResponse)

	if err != nil {
		return err
	}

	*o = UserspbCreateUserResponse(varUserspbCreateUserResponse)

	return err
}

type NullableUserspbCreateUserResponse struct {
	value *UserspbCreateUserResponse
	isSet bool
}

func (v NullableUserspbCreateUserResponse) Get() *UserspbCreateUserResponse {
	return v.value
}

func (v *NullableUserspbCreateUserResponse) Set(val *UserspbCreateUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserspbCreateUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserspbCreateUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserspbCreateUserResponse(val *UserspbCreateUserResponse) *NullableUserspbCreateUserResponse {
	return &NullableUserspbCreateUserResponse{value: val, isSet: true}
}

func (v NullableUserspbCreateUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserspbCreateUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


