/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"fmt"
)

// UserspbGenderValue the model 'UserspbGenderValue'
type UserspbGenderValue int32

// List of userspb.GenderValue
const (
	GenderValue_GENDER_UNSPECIFIED UserspbGenderValue = 0
	GenderValue_GENDER_UNSELECTED UserspbGenderValue = 1
	GenderValue_GENDER_MALE UserspbGenderValue = 2
	GenderValue_GENDER_FEMALE UserspbGenderValue = 3
)

// All allowed values of UserspbGenderValue enum
var AllowedUserspbGenderValueEnumValues = []UserspbGenderValue{
	0,
	1,
	2,
	3,
}

func (v *UserspbGenderValue) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UserspbGenderValue(value)
	for _, existing := range AllowedUserspbGenderValueEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UserspbGenderValue", value)
}

// NewUserspbGenderValueFromValue returns a pointer to a valid UserspbGenderValue
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUserspbGenderValueFromValue(v int32) (*UserspbGenderValue, error) {
	ev := UserspbGenderValue(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UserspbGenderValue: valid values are %v", v, AllowedUserspbGenderValueEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UserspbGenderValue) IsValid() bool {
	for _, existing := range AllowedUserspbGenderValueEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to userspb.GenderValue value
func (v UserspbGenderValue) Ptr() *UserspbGenderValue {
	return &v
}

type NullableUserspbGenderValue struct {
	value *UserspbGenderValue
	isSet bool
}

func (v NullableUserspbGenderValue) Get() *UserspbGenderValue {
	return v.value
}

func (v *NullableUserspbGenderValue) Set(val *UserspbGenderValue) {
	v.value = val
	v.isSet = true
}

func (v NullableUserspbGenderValue) IsSet() bool {
	return v.isSet
}

func (v *NullableUserspbGenderValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserspbGenderValue(val *UserspbGenderValue) *NullableUserspbGenderValue {
	return &NullableUserspbGenderValue{value: val, isSet: true}
}

func (v NullableUserspbGenderValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserspbGenderValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

