/*
Swagger Documentation for microservices shop API Gateway

Swagger Documentation for API Gateway of microservices shop project

API version: 1.0
Contact: f3d0t0tvmax@yandex.ru
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserspbUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserspbUser{}

// UserspbUser struct for UserspbUser
type UserspbUser struct {
	CreatedAt TimestamppbTimestamp `json:"created_at"`
	Email string `json:"email"`
	Id string `json:"id"`
	Phone *string `json:"phone,omitempty"`
	Profile UserspbProfile `json:"profile"`
	UpdatedAt TimestamppbTimestamp `json:"updated_at"`
}

type _UserspbUser UserspbUser

// NewUserspbUser instantiates a new UserspbUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserspbUser(createdAt TimestamppbTimestamp, email string, id string, profile UserspbProfile, updatedAt TimestamppbTimestamp) *UserspbUser {
	this := UserspbUser{}
	this.CreatedAt = createdAt
	this.Email = email
	this.Id = id
	this.Profile = profile
	this.UpdatedAt = updatedAt
	return &this
}

// NewUserspbUserWithDefaults instantiates a new UserspbUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserspbUserWithDefaults() *UserspbUser {
	this := UserspbUser{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *UserspbUser) GetCreatedAt() TimestamppbTimestamp {
	if o == nil {
		var ret TimestamppbTimestamp
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UserspbUser) GetCreatedAtOk() (*TimestamppbTimestamp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UserspbUser) SetCreatedAt(v TimestamppbTimestamp) {
	o.CreatedAt = v
}

// GetEmail returns the Email field value
func (o *UserspbUser) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserspbUser) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserspbUser) SetEmail(v string) {
	o.Email = v
}

// GetId returns the Id field value
func (o *UserspbUser) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserspbUser) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserspbUser) SetId(v string) {
	o.Id = v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *UserspbUser) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserspbUser) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *UserspbUser) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *UserspbUser) SetPhone(v string) {
	o.Phone = &v
}

// GetProfile returns the Profile field value
func (o *UserspbUser) GetProfile() UserspbProfile {
	if o == nil {
		var ret UserspbProfile
		return ret
	}

	return o.Profile
}

// GetProfileOk returns a tuple with the Profile field value
// and a boolean to check if the value has been set.
func (o *UserspbUser) GetProfileOk() (*UserspbProfile, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Profile, true
}

// SetProfile sets field value
func (o *UserspbUser) SetProfile(v UserspbProfile) {
	o.Profile = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UserspbUser) GetUpdatedAt() TimestamppbTimestamp {
	if o == nil {
		var ret TimestamppbTimestamp
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UserspbUser) GetUpdatedAtOk() (*TimestamppbTimestamp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UserspbUser) SetUpdatedAt(v TimestamppbTimestamp) {
	o.UpdatedAt = v
}

func (o UserspbUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserspbUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["email"] = o.Email
	toSerialize["id"] = o.Id
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	toSerialize["profile"] = o.Profile
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *UserspbUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"email",
		"id",
		"profile",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserspbUser := _UserspbUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserspbUser)

	if err != nil {
		return err
	}

	*o = UserspbUser(varUserspbUser)

	return err
}

type NullableUserspbUser struct {
	value *UserspbUser
	isSet bool
}

func (v NullableUserspbUser) Get() *UserspbUser {
	return v.value
}

func (v *NullableUserspbUser) Set(val *UserspbUser) {
	v.value = val
	v.isSet = true
}

func (v NullableUserspbUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUserspbUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserspbUser(val *UserspbUser) *NullableUserspbUser {
	return &NullableUserspbUser{value: val, isSet: true}
}

func (v NullableUserspbUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserspbUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


