// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new customers API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new customers API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new customers API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for customers API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetCustomersUsersProfile(params *GetCustomersUsersProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCustomersUsersProfileOK, error)

	PatchCustomersUsersProfile(params *PatchCustomersUsersProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchCustomersUsersProfileOK, error)

	PostCustomersSessionLogin(params *PostCustomersSessionLoginParams, opts ...ClientOption) (*PostCustomersSessionLoginOK, *PostCustomersSessionLoginStatus228, error)

	PostCustomersSessionRefreshSession(params *PostCustomersSessionRefreshSessionParams, opts ...ClientOption) (*PostCustomersSessionRefreshSessionCreated, error)

	PostCustomersUsers(params *PostCustomersUsersParams, opts ...ClientOption) (*PostCustomersUsersCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetCustomersUsersProfile gets user profile

Get user base profile
*/
func (a *Client) GetCustomersUsersProfile(params *GetCustomersUsersProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCustomersUsersProfileOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetCustomersUsersProfileParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCustomersUsersProfile",
		Method:             "GET",
		PathPattern:        "/customers/users/profile",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCustomersUsersProfileReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetCustomersUsersProfileOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCustomersUsersProfile: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PatchCustomersUsersProfile updates user profile

Update user profile
*/
func (a *Client) PatchCustomersUsersProfile(params *PatchCustomersUsersProfileParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PatchCustomersUsersProfileOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPatchCustomersUsersProfileParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PatchCustomersUsersProfile",
		Method:             "PATCH",
		PathPattern:        "/customers/users/profile",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchCustomersUsersProfileReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PatchCustomersUsersProfileOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PatchCustomersUsersProfile: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostCustomersSessionLogin logins in account

Login in account
*/
func (a *Client) PostCustomersSessionLogin(params *PostCustomersSessionLoginParams, opts ...ClientOption) (*PostCustomersSessionLoginOK, *PostCustomersSessionLoginStatus228, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostCustomersSessionLoginParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostCustomersSessionLogin",
		Method:             "POST",
		PathPattern:        "/customers/session/login",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostCustomersSessionLoginReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}

	// several success responses have to be checked
	switch value := result.(type) {
	case *PostCustomersSessionLoginOK:
		return value, nil, nil
	case *PostCustomersSessionLoginStatus228:
		return nil, value, nil
	}

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for customers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostCustomersSessionRefreshSession refreshes session

Refresh session by refresh token from headers
*/
func (a *Client) PostCustomersSessionRefreshSession(params *PostCustomersSessionRefreshSessionParams, opts ...ClientOption) (*PostCustomersSessionRefreshSessionCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostCustomersSessionRefreshSessionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostCustomersSessionRefreshSession",
		Method:             "POST",
		PathPattern:        "/customers/session/refresh-session",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostCustomersSessionRefreshSessionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostCustomersSessionRefreshSessionCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostCustomersSessionRefreshSession: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostCustomersUsers creates user account

Create new user account
*/
func (a *Client) PostCustomersUsers(params *PostCustomersUsersParams, opts ...ClientOption) (*PostCustomersUsersCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostCustomersUsersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostCustomersUsers",
		Method:             "POST",
		PathPattern:        "/customers/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostCustomersUsersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostCustomersUsersCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostCustomersUsers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
