// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// GetCustomersUsersIDReader is a Reader for the GetCustomersUsersID structure.
type GetCustomersUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomersUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomersUsersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCustomersUsersIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCustomersUsersIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCustomersUsersIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /customers/users/{id}] GetCustomersUsersID", response, response.Code())
	}
}

// NewGetCustomersUsersIDOK creates a GetCustomersUsersIDOK with default headers values
func NewGetCustomersUsersIDOK() *GetCustomersUsersIDOK {
	return &GetCustomersUsersIDOK{}
}

/*
GetCustomersUsersIDOK describes a response with status code 200, with default header values.

OK
*/
type GetCustomersUsersIDOK struct {
	Payload *models.UserspbUser
}

// IsSuccess returns true when this get customers users Id o k response has a 2xx status code
func (o *GetCustomersUsersIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customers users Id o k response has a 3xx status code
func (o *GetCustomersUsersIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers users Id o k response has a 4xx status code
func (o *GetCustomersUsersIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers users Id o k response has a 5xx status code
func (o *GetCustomersUsersIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers users Id o k response a status code equal to that given
func (o *GetCustomersUsersIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get customers users Id o k response
func (o *GetCustomersUsersIDOK) Code() int {
	return 200
}

func (o *GetCustomersUsersIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/{id}][%d] getCustomersUsersIdOK %s", 200, payload)
}

func (o *GetCustomersUsersIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/{id}][%d] getCustomersUsersIdOK %s", 200, payload)
}

func (o *GetCustomersUsersIDOK) GetPayload() *models.UserspbUser {
	return o.Payload
}

func (o *GetCustomersUsersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserspbUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCustomersUsersIDBadRequest creates a GetCustomersUsersIDBadRequest with default headers values
func NewGetCustomersUsersIDBadRequest() *GetCustomersUsersIDBadRequest {
	return &GetCustomersUsersIDBadRequest{}
}

/*
GetCustomersUsersIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetCustomersUsersIDBadRequest struct {
	Payload *models.ErrdetailsBadRequest
}

// IsSuccess returns true when this get customers users Id bad request response has a 2xx status code
func (o *GetCustomersUsersIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get customers users Id bad request response has a 3xx status code
func (o *GetCustomersUsersIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers users Id bad request response has a 4xx status code
func (o *GetCustomersUsersIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get customers users Id bad request response has a 5xx status code
func (o *GetCustomersUsersIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers users Id bad request response a status code equal to that given
func (o *GetCustomersUsersIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get customers users Id bad request response
func (o *GetCustomersUsersIDBadRequest) Code() int {
	return 400
}

func (o *GetCustomersUsersIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/{id}][%d] getCustomersUsersIdBadRequest %s", 400, payload)
}

func (o *GetCustomersUsersIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/{id}][%d] getCustomersUsersIdBadRequest %s", 400, payload)
}

func (o *GetCustomersUsersIDBadRequest) GetPayload() *models.ErrdetailsBadRequest {
	return o.Payload
}

func (o *GetCustomersUsersIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrdetailsBadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCustomersUsersIDNotFound creates a GetCustomersUsersIDNotFound with default headers values
func NewGetCustomersUsersIDNotFound() *GetCustomersUsersIDNotFound {
	return &GetCustomersUsersIDNotFound{}
}

/*
GetCustomersUsersIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetCustomersUsersIDNotFound struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this get customers users Id not found response has a 2xx status code
func (o *GetCustomersUsersIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get customers users Id not found response has a 3xx status code
func (o *GetCustomersUsersIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers users Id not found response has a 4xx status code
func (o *GetCustomersUsersIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get customers users Id not found response has a 5xx status code
func (o *GetCustomersUsersIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers users Id not found response a status code equal to that given
func (o *GetCustomersUsersIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get customers users Id not found response
func (o *GetCustomersUsersIDNotFound) Code() int {
	return 404
}

func (o *GetCustomersUsersIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/{id}][%d] getCustomersUsersIdNotFound %s", 404, payload)
}

func (o *GetCustomersUsersIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/{id}][%d] getCustomersUsersIdNotFound %s", 404, payload)
}

func (o *GetCustomersUsersIDNotFound) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *GetCustomersUsersIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCustomersUsersIDInternalServerError creates a GetCustomersUsersIDInternalServerError with default headers values
func NewGetCustomersUsersIDInternalServerError() *GetCustomersUsersIDInternalServerError {
	return &GetCustomersUsersIDInternalServerError{}
}

/*
GetCustomersUsersIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetCustomersUsersIDInternalServerError struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this get customers users Id internal server error response has a 2xx status code
func (o *GetCustomersUsersIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get customers users Id internal server error response has a 3xx status code
func (o *GetCustomersUsersIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers users Id internal server error response has a 4xx status code
func (o *GetCustomersUsersIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers users Id internal server error response has a 5xx status code
func (o *GetCustomersUsersIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get customers users Id internal server error response a status code equal to that given
func (o *GetCustomersUsersIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get customers users Id internal server error response
func (o *GetCustomersUsersIDInternalServerError) Code() int {
	return 500
}

func (o *GetCustomersUsersIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/{id}][%d] getCustomersUsersIdInternalServerError %s", 500, payload)
}

func (o *GetCustomersUsersIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/{id}][%d] getCustomersUsersIdInternalServerError %s", 500, payload)
}

func (o *GetCustomersUsersIDInternalServerError) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *GetCustomersUsersIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
