// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomersUsersProfileParams creates a new GetCustomersUsersProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCustomersUsersProfileParams() *GetCustomersUsersProfileParams {
	return &GetCustomersUsersProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomersUsersProfileParamsWithTimeout creates a new GetCustomersUsersProfileParams object
// with the ability to set a timeout on a request.
func NewGetCustomersUsersProfileParamsWithTimeout(timeout time.Duration) *GetCustomersUsersProfileParams {
	return &GetCustomersUsersProfileParams{
		timeout: timeout,
	}
}

// NewGetCustomersUsersProfileParamsWithContext creates a new GetCustomersUsersProfileParams object
// with the ability to set a context for a request.
func NewGetCustomersUsersProfileParamsWithContext(ctx context.Context) *GetCustomersUsersProfileParams {
	return &GetCustomersUsersProfileParams{
		Context: ctx,
	}
}

// NewGetCustomersUsersProfileParamsWithHTTPClient creates a new GetCustomersUsersProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCustomersUsersProfileParamsWithHTTPClient(client *http.Client) *GetCustomersUsersProfileParams {
	return &GetCustomersUsersProfileParams{
		HTTPClient: client,
	}
}

/*
GetCustomersUsersProfileParams contains all the parameters to send to the API endpoint

	for the get customers users profile operation.

	Typically these are written to a http.Request.
*/
type GetCustomersUsersProfileParams struct {

	/* XRequestLocale.

	   Locale
	*/
	XRequestLocale *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get customers users profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersUsersProfileParams) WithDefaults() *GetCustomersUsersProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get customers users profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersUsersProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get customers users profile params
func (o *GetCustomersUsersProfileParams) WithTimeout(timeout time.Duration) *GetCustomersUsersProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customers users profile params
func (o *GetCustomersUsersProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customers users profile params
func (o *GetCustomersUsersProfileParams) WithContext(ctx context.Context) *GetCustomersUsersProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customers users profile params
func (o *GetCustomersUsersProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customers users profile params
func (o *GetCustomersUsersProfileParams) WithHTTPClient(client *http.Client) *GetCustomersUsersProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customers users profile params
func (o *GetCustomersUsersProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestLocale adds the xRequestLocale to the get customers users profile params
func (o *GetCustomersUsersProfileParams) WithXRequestLocale(xRequestLocale *string) *GetCustomersUsersProfileParams {
	o.SetXRequestLocale(xRequestLocale)
	return o
}

// SetXRequestLocale adds the xRequestLocale to the get customers users profile params
func (o *GetCustomersUsersProfileParams) SetXRequestLocale(xRequestLocale *string) {
	o.XRequestLocale = xRequestLocale
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomersUsersProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestLocale != nil {

		// header param X-Request-Locale
		if err := r.SetHeaderParam("X-Request-Locale", *o.XRequestLocale); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
