// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// GetCustomersUsersProfileReader is a Reader for the GetCustomersUsersProfile structure.
type GetCustomersUsersProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomersUsersProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomersUsersProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCustomersUsersProfileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetCustomersUsersProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCustomersUsersProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCustomersUsersProfileInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /customers/users/profile] GetCustomersUsersProfile", response, response.Code())
	}
}

// NewGetCustomersUsersProfileOK creates a GetCustomersUsersProfileOK with default headers values
func NewGetCustomersUsersProfileOK() *GetCustomersUsersProfileOK {
	return &GetCustomersUsersProfileOK{}
}

/*
GetCustomersUsersProfileOK describes a response with status code 200, with default header values.

OK
*/
type GetCustomersUsersProfileOK struct {
	Payload *models.UserspbUser
}

// IsSuccess returns true when this get customers users profile o k response has a 2xx status code
func (o *GetCustomersUsersProfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customers users profile o k response has a 3xx status code
func (o *GetCustomersUsersProfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers users profile o k response has a 4xx status code
func (o *GetCustomersUsersProfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers users profile o k response has a 5xx status code
func (o *GetCustomersUsersProfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers users profile o k response a status code equal to that given
func (o *GetCustomersUsersProfileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get customers users profile o k response
func (o *GetCustomersUsersProfileOK) Code() int {
	return 200
}

func (o *GetCustomersUsersProfileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileOK %s", 200, payload)
}

func (o *GetCustomersUsersProfileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileOK %s", 200, payload)
}

func (o *GetCustomersUsersProfileOK) GetPayload() *models.UserspbUser {
	return o.Payload
}

func (o *GetCustomersUsersProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserspbUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCustomersUsersProfileBadRequest creates a GetCustomersUsersProfileBadRequest with default headers values
func NewGetCustomersUsersProfileBadRequest() *GetCustomersUsersProfileBadRequest {
	return &GetCustomersUsersProfileBadRequest{}
}

/*
GetCustomersUsersProfileBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetCustomersUsersProfileBadRequest struct {
	Payload *models.ErrdetailsBadRequest
}

// IsSuccess returns true when this get customers users profile bad request response has a 2xx status code
func (o *GetCustomersUsersProfileBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get customers users profile bad request response has a 3xx status code
func (o *GetCustomersUsersProfileBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers users profile bad request response has a 4xx status code
func (o *GetCustomersUsersProfileBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get customers users profile bad request response has a 5xx status code
func (o *GetCustomersUsersProfileBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers users profile bad request response a status code equal to that given
func (o *GetCustomersUsersProfileBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get customers users profile bad request response
func (o *GetCustomersUsersProfileBadRequest) Code() int {
	return 400
}

func (o *GetCustomersUsersProfileBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileBadRequest %s", 400, payload)
}

func (o *GetCustomersUsersProfileBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileBadRequest %s", 400, payload)
}

func (o *GetCustomersUsersProfileBadRequest) GetPayload() *models.ErrdetailsBadRequest {
	return o.Payload
}

func (o *GetCustomersUsersProfileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrdetailsBadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCustomersUsersProfileUnauthorized creates a GetCustomersUsersProfileUnauthorized with default headers values
func NewGetCustomersUsersProfileUnauthorized() *GetCustomersUsersProfileUnauthorized {
	return &GetCustomersUsersProfileUnauthorized{}
}

/*
GetCustomersUsersProfileUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetCustomersUsersProfileUnauthorized struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this get customers users profile unauthorized response has a 2xx status code
func (o *GetCustomersUsersProfileUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get customers users profile unauthorized response has a 3xx status code
func (o *GetCustomersUsersProfileUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers users profile unauthorized response has a 4xx status code
func (o *GetCustomersUsersProfileUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get customers users profile unauthorized response has a 5xx status code
func (o *GetCustomersUsersProfileUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers users profile unauthorized response a status code equal to that given
func (o *GetCustomersUsersProfileUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get customers users profile unauthorized response
func (o *GetCustomersUsersProfileUnauthorized) Code() int {
	return 401
}

func (o *GetCustomersUsersProfileUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileUnauthorized %s", 401, payload)
}

func (o *GetCustomersUsersProfileUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileUnauthorized %s", 401, payload)
}

func (o *GetCustomersUsersProfileUnauthorized) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *GetCustomersUsersProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCustomersUsersProfileNotFound creates a GetCustomersUsersProfileNotFound with default headers values
func NewGetCustomersUsersProfileNotFound() *GetCustomersUsersProfileNotFound {
	return &GetCustomersUsersProfileNotFound{}
}

/*
GetCustomersUsersProfileNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetCustomersUsersProfileNotFound struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this get customers users profile not found response has a 2xx status code
func (o *GetCustomersUsersProfileNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get customers users profile not found response has a 3xx status code
func (o *GetCustomersUsersProfileNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers users profile not found response has a 4xx status code
func (o *GetCustomersUsersProfileNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get customers users profile not found response has a 5xx status code
func (o *GetCustomersUsersProfileNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get customers users profile not found response a status code equal to that given
func (o *GetCustomersUsersProfileNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get customers users profile not found response
func (o *GetCustomersUsersProfileNotFound) Code() int {
	return 404
}

func (o *GetCustomersUsersProfileNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileNotFound %s", 404, payload)
}

func (o *GetCustomersUsersProfileNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileNotFound %s", 404, payload)
}

func (o *GetCustomersUsersProfileNotFound) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *GetCustomersUsersProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCustomersUsersProfileInternalServerError creates a GetCustomersUsersProfileInternalServerError with default headers values
func NewGetCustomersUsersProfileInternalServerError() *GetCustomersUsersProfileInternalServerError {
	return &GetCustomersUsersProfileInternalServerError{}
}

/*
GetCustomersUsersProfileInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetCustomersUsersProfileInternalServerError struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this get customers users profile internal server error response has a 2xx status code
func (o *GetCustomersUsersProfileInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get customers users profile internal server error response has a 3xx status code
func (o *GetCustomersUsersProfileInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customers users profile internal server error response has a 4xx status code
func (o *GetCustomersUsersProfileInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customers users profile internal server error response has a 5xx status code
func (o *GetCustomersUsersProfileInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get customers users profile internal server error response a status code equal to that given
func (o *GetCustomersUsersProfileInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get customers users profile internal server error response
func (o *GetCustomersUsersProfileInternalServerError) Code() int {
	return 500
}

func (o *GetCustomersUsersProfileInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileInternalServerError %s", 500, payload)
}

func (o *GetCustomersUsersProfileInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /customers/users/profile][%d] getCustomersUsersProfileInternalServerError %s", 500, payload)
}

func (o *GetCustomersUsersProfileInternalServerError) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *GetCustomersUsersProfileInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
