// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomersUsersIDParams creates a new GetCustomersUsersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCustomersUsersIDParams() *GetCustomersUsersIDParams {
	return &GetCustomersUsersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomersUsersIDParamsWithTimeout creates a new GetCustomersUsersIDParams object
// with the ability to set a timeout on a request.
func NewGetCustomersUsersIDParamsWithTimeout(timeout time.Duration) *GetCustomersUsersIDParams {
	return &GetCustomersUsersIDParams{
		timeout: timeout,
	}
}

// NewGetCustomersUsersIDParamsWithContext creates a new GetCustomersUsersIDParams object
// with the ability to set a context for a request.
func NewGetCustomersUsersIDParamsWithContext(ctx context.Context) *GetCustomersUsersIDParams {
	return &GetCustomersUsersIDParams{
		Context: ctx,
	}
}

// NewGetCustomersUsersIDParamsWithHTTPClient creates a new GetCustomersUsersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCustomersUsersIDParamsWithHTTPClient(client *http.Client) *GetCustomersUsersIDParams {
	return &GetCustomersUsersIDParams{
		HTTPClient: client,
	}
}

/*
GetCustomersUsersIDParams contains all the parameters to send to the API endpoint

	for the get customers users ID operation.

	Typically these are written to a http.Request.
*/
type GetCustomersUsersIDParams struct {

	/* XRequestLocale.

	   Locale
	*/
	XRequestLocale *string

	/* ID.

	   User id parameter
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get customers users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersUsersIDParams) WithDefaults() *GetCustomersUsersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get customers users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomersUsersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get customers users ID params
func (o *GetCustomersUsersIDParams) WithTimeout(timeout time.Duration) *GetCustomersUsersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customers users ID params
func (o *GetCustomersUsersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customers users ID params
func (o *GetCustomersUsersIDParams) WithContext(ctx context.Context) *GetCustomersUsersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customers users ID params
func (o *GetCustomersUsersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customers users ID params
func (o *GetCustomersUsersIDParams) WithHTTPClient(client *http.Client) *GetCustomersUsersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customers users ID params
func (o *GetCustomersUsersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestLocale adds the xRequestLocale to the get customers users ID params
func (o *GetCustomersUsersIDParams) WithXRequestLocale(xRequestLocale *string) *GetCustomersUsersIDParams {
	o.SetXRequestLocale(xRequestLocale)
	return o
}

// SetXRequestLocale adds the xRequestLocale to the get customers users ID params
func (o *GetCustomersUsersIDParams) SetXRequestLocale(xRequestLocale *string) {
	o.XRequestLocale = xRequestLocale
}

// WithID adds the id to the get customers users ID params
func (o *GetCustomersUsersIDParams) WithID(id string) *GetCustomersUsersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get customers users ID params
func (o *GetCustomersUsersIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomersUsersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestLocale != nil {

		// header param X-Request-Locale
		if err := r.SetHeaderParam("X-Request-Locale", *o.XRequestLocale); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
