// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// NewPatchCustomersUsersProfileParams creates a new PatchCustomersUsersProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchCustomersUsersProfileParams() *PatchCustomersUsersProfileParams {
	return &PatchCustomersUsersProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchCustomersUsersProfileParamsWithTimeout creates a new PatchCustomersUsersProfileParams object
// with the ability to set a timeout on a request.
func NewPatchCustomersUsersProfileParamsWithTimeout(timeout time.Duration) *PatchCustomersUsersProfileParams {
	return &PatchCustomersUsersProfileParams{
		timeout: timeout,
	}
}

// NewPatchCustomersUsersProfileParamsWithContext creates a new PatchCustomersUsersProfileParams object
// with the ability to set a context for a request.
func NewPatchCustomersUsersProfileParamsWithContext(ctx context.Context) *PatchCustomersUsersProfileParams {
	return &PatchCustomersUsersProfileParams{
		Context: ctx,
	}
}

// NewPatchCustomersUsersProfileParamsWithHTTPClient creates a new PatchCustomersUsersProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchCustomersUsersProfileParamsWithHTTPClient(client *http.Client) *PatchCustomersUsersProfileParams {
	return &PatchCustomersUsersProfileParams{
		HTTPClient: client,
	}
}

/*
PatchCustomersUsersProfileParams contains all the parameters to send to the API endpoint

	for the patch customers users profile operation.

	Typically these are written to a http.Request.
*/
type PatchCustomersUsersProfileParams struct {

	/* XRequestLocale.

	   Locale
	*/
	XRequestLocale *string

	/* Dto.

	   Update user profile with body dto
	*/
	Dto *models.UserspbUpdateUserProfileData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch customers users profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchCustomersUsersProfileParams) WithDefaults() *PatchCustomersUsersProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch customers users profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchCustomersUsersProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) WithTimeout(timeout time.Duration) *PatchCustomersUsersProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) WithContext(ctx context.Context) *PatchCustomersUsersProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) WithHTTPClient(client *http.Client) *PatchCustomersUsersProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestLocale adds the xRequestLocale to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) WithXRequestLocale(xRequestLocale *string) *PatchCustomersUsersProfileParams {
	o.SetXRequestLocale(xRequestLocale)
	return o
}

// SetXRequestLocale adds the xRequestLocale to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) SetXRequestLocale(xRequestLocale *string) {
	o.XRequestLocale = xRequestLocale
}

// WithDto adds the dto to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) WithDto(dto *models.UserspbUpdateUserProfileData) *PatchCustomersUsersProfileParams {
	o.SetDto(dto)
	return o
}

// SetDto adds the dto to the patch customers users profile params
func (o *PatchCustomersUsersProfileParams) SetDto(dto *models.UserspbUpdateUserProfileData) {
	o.Dto = dto
}

// WriteToRequest writes these params to a swagger request
func (o *PatchCustomersUsersProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestLocale != nil {

		// header param X-Request-Locale
		if err := r.SetHeaderParam("X-Request-Locale", *o.XRequestLocale); err != nil {
			return err
		}
	}
	if o.Dto != nil {
		if err := r.SetBodyParam(o.Dto); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
