// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// NewPatchCustomersUsersIDParams creates a new PatchCustomersUsersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchCustomersUsersIDParams() *PatchCustomersUsersIDParams {
	return &PatchCustomersUsersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchCustomersUsersIDParamsWithTimeout creates a new PatchCustomersUsersIDParams object
// with the ability to set a timeout on a request.
func NewPatchCustomersUsersIDParamsWithTimeout(timeout time.Duration) *PatchCustomersUsersIDParams {
	return &PatchCustomersUsersIDParams{
		timeout: timeout,
	}
}

// NewPatchCustomersUsersIDParamsWithContext creates a new PatchCustomersUsersIDParams object
// with the ability to set a context for a request.
func NewPatchCustomersUsersIDParamsWithContext(ctx context.Context) *PatchCustomersUsersIDParams {
	return &PatchCustomersUsersIDParams{
		Context: ctx,
	}
}

// NewPatchCustomersUsersIDParamsWithHTTPClient creates a new PatchCustomersUsersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchCustomersUsersIDParamsWithHTTPClient(client *http.Client) *PatchCustomersUsersIDParams {
	return &PatchCustomersUsersIDParams{
		HTTPClient: client,
	}
}

/*
PatchCustomersUsersIDParams contains all the parameters to send to the API endpoint

	for the patch customers users ID operation.

	Typically these are written to a http.Request.
*/
type PatchCustomersUsersIDParams struct {

	/* XRequestLocale.

	   Locale
	*/
	XRequestLocale *string

	/* Dto.

	   Update user profile with body dto
	*/
	Dto *models.UserspbUpdateUserProfileData

	/* ID.

	   User id parameter
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch customers users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchCustomersUsersIDParams) WithDefaults() *PatchCustomersUsersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch customers users ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchCustomersUsersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) WithTimeout(timeout time.Duration) *PatchCustomersUsersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) WithContext(ctx context.Context) *PatchCustomersUsersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) WithHTTPClient(client *http.Client) *PatchCustomersUsersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestLocale adds the xRequestLocale to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) WithXRequestLocale(xRequestLocale *string) *PatchCustomersUsersIDParams {
	o.SetXRequestLocale(xRequestLocale)
	return o
}

// SetXRequestLocale adds the xRequestLocale to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) SetXRequestLocale(xRequestLocale *string) {
	o.XRequestLocale = xRequestLocale
}

// WithDto adds the dto to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) WithDto(dto *models.UserspbUpdateUserProfileData) *PatchCustomersUsersIDParams {
	o.SetDto(dto)
	return o
}

// SetDto adds the dto to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) SetDto(dto *models.UserspbUpdateUserProfileData) {
	o.Dto = dto
}

// WithID adds the id to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) WithID(id string) *PatchCustomersUsersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch customers users ID params
func (o *PatchCustomersUsersIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchCustomersUsersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestLocale != nil {

		// header param X-Request-Locale
		if err := r.SetHeaderParam("X-Request-Locale", *o.XRequestLocale); err != nil {
			return err
		}
	}
	if o.Dto != nil {
		if err := r.SetBodyParam(o.Dto); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
