// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// PatchCustomersUsersProfileReader is a Reader for the PatchCustomersUsersProfile structure.
type PatchCustomersUsersProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchCustomersUsersProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPatchCustomersUsersProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchCustomersUsersProfileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPatchCustomersUsersProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPatchCustomersUsersProfileInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /customers/users/profile] PatchCustomersUsersProfile", response, response.Code())
	}
}

// NewPatchCustomersUsersProfileOK creates a PatchCustomersUsersProfileOK with default headers values
func NewPatchCustomersUsersProfileOK() *PatchCustomersUsersProfileOK {
	return &PatchCustomersUsersProfileOK{}
}

/*
PatchCustomersUsersProfileOK describes a response with status code 200, with default header values.

OK
*/
type PatchCustomersUsersProfileOK struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this patch customers users profile o k response has a 2xx status code
func (o *PatchCustomersUsersProfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch customers users profile o k response has a 3xx status code
func (o *PatchCustomersUsersProfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch customers users profile o k response has a 4xx status code
func (o *PatchCustomersUsersProfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch customers users profile o k response has a 5xx status code
func (o *PatchCustomersUsersProfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch customers users profile o k response a status code equal to that given
func (o *PatchCustomersUsersProfileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch customers users profile o k response
func (o *PatchCustomersUsersProfileOK) Code() int {
	return 200
}

func (o *PatchCustomersUsersProfileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/profile][%d] patchCustomersUsersProfileOK %s", 200, payload)
}

func (o *PatchCustomersUsersProfileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/profile][%d] patchCustomersUsersProfileOK %s", 200, payload)
}

func (o *PatchCustomersUsersProfileOK) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PatchCustomersUsersProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchCustomersUsersProfileBadRequest creates a PatchCustomersUsersProfileBadRequest with default headers values
func NewPatchCustomersUsersProfileBadRequest() *PatchCustomersUsersProfileBadRequest {
	return &PatchCustomersUsersProfileBadRequest{}
}

/*
PatchCustomersUsersProfileBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PatchCustomersUsersProfileBadRequest struct {
	Payload *models.ErrdetailsBadRequest
}

// IsSuccess returns true when this patch customers users profile bad request response has a 2xx status code
func (o *PatchCustomersUsersProfileBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch customers users profile bad request response has a 3xx status code
func (o *PatchCustomersUsersProfileBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch customers users profile bad request response has a 4xx status code
func (o *PatchCustomersUsersProfileBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch customers users profile bad request response has a 5xx status code
func (o *PatchCustomersUsersProfileBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this patch customers users profile bad request response a status code equal to that given
func (o *PatchCustomersUsersProfileBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the patch customers users profile bad request response
func (o *PatchCustomersUsersProfileBadRequest) Code() int {
	return 400
}

func (o *PatchCustomersUsersProfileBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/profile][%d] patchCustomersUsersProfileBadRequest %s", 400, payload)
}

func (o *PatchCustomersUsersProfileBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/profile][%d] patchCustomersUsersProfileBadRequest %s", 400, payload)
}

func (o *PatchCustomersUsersProfileBadRequest) GetPayload() *models.ErrdetailsBadRequest {
	return o.Payload
}

func (o *PatchCustomersUsersProfileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrdetailsBadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchCustomersUsersProfileUnauthorized creates a PatchCustomersUsersProfileUnauthorized with default headers values
func NewPatchCustomersUsersProfileUnauthorized() *PatchCustomersUsersProfileUnauthorized {
	return &PatchCustomersUsersProfileUnauthorized{}
}

/*
PatchCustomersUsersProfileUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PatchCustomersUsersProfileUnauthorized struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this patch customers users profile unauthorized response has a 2xx status code
func (o *PatchCustomersUsersProfileUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch customers users profile unauthorized response has a 3xx status code
func (o *PatchCustomersUsersProfileUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch customers users profile unauthorized response has a 4xx status code
func (o *PatchCustomersUsersProfileUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch customers users profile unauthorized response has a 5xx status code
func (o *PatchCustomersUsersProfileUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this patch customers users profile unauthorized response a status code equal to that given
func (o *PatchCustomersUsersProfileUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the patch customers users profile unauthorized response
func (o *PatchCustomersUsersProfileUnauthorized) Code() int {
	return 401
}

func (o *PatchCustomersUsersProfileUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/profile][%d] patchCustomersUsersProfileUnauthorized %s", 401, payload)
}

func (o *PatchCustomersUsersProfileUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/profile][%d] patchCustomersUsersProfileUnauthorized %s", 401, payload)
}

func (o *PatchCustomersUsersProfileUnauthorized) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PatchCustomersUsersProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchCustomersUsersProfileInternalServerError creates a PatchCustomersUsersProfileInternalServerError with default headers values
func NewPatchCustomersUsersProfileInternalServerError() *PatchCustomersUsersProfileInternalServerError {
	return &PatchCustomersUsersProfileInternalServerError{}
}

/*
PatchCustomersUsersProfileInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PatchCustomersUsersProfileInternalServerError struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this patch customers users profile internal server error response has a 2xx status code
func (o *PatchCustomersUsersProfileInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch customers users profile internal server error response has a 3xx status code
func (o *PatchCustomersUsersProfileInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch customers users profile internal server error response has a 4xx status code
func (o *PatchCustomersUsersProfileInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch customers users profile internal server error response has a 5xx status code
func (o *PatchCustomersUsersProfileInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this patch customers users profile internal server error response a status code equal to that given
func (o *PatchCustomersUsersProfileInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the patch customers users profile internal server error response
func (o *PatchCustomersUsersProfileInternalServerError) Code() int {
	return 500
}

func (o *PatchCustomersUsersProfileInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/profile][%d] patchCustomersUsersProfileInternalServerError %s", 500, payload)
}

func (o *PatchCustomersUsersProfileInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/profile][%d] patchCustomersUsersProfileInternalServerError %s", 500, payload)
}

func (o *PatchCustomersUsersProfileInternalServerError) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PatchCustomersUsersProfileInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
