// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// PatchCustomersUsersIDReader is a Reader for the PatchCustomersUsersID structure.
type PatchCustomersUsersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchCustomersUsersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPatchCustomersUsersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchCustomersUsersIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPatchCustomersUsersIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /customers/users/{id}] PatchCustomersUsersID", response, response.Code())
	}
}

// NewPatchCustomersUsersIDOK creates a PatchCustomersUsersIDOK with default headers values
func NewPatchCustomersUsersIDOK() *PatchCustomersUsersIDOK {
	return &PatchCustomersUsersIDOK{}
}

/*
PatchCustomersUsersIDOK describes a response with status code 200, with default header values.

OK
*/
type PatchCustomersUsersIDOK struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this patch customers users Id o k response has a 2xx status code
func (o *PatchCustomersUsersIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch customers users Id o k response has a 3xx status code
func (o *PatchCustomersUsersIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch customers users Id o k response has a 4xx status code
func (o *PatchCustomersUsersIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch customers users Id o k response has a 5xx status code
func (o *PatchCustomersUsersIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch customers users Id o k response a status code equal to that given
func (o *PatchCustomersUsersIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch customers users Id o k response
func (o *PatchCustomersUsersIDOK) Code() int {
	return 200
}

func (o *PatchCustomersUsersIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/{id}][%d] patchCustomersUsersIdOK %s", 200, payload)
}

func (o *PatchCustomersUsersIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/{id}][%d] patchCustomersUsersIdOK %s", 200, payload)
}

func (o *PatchCustomersUsersIDOK) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PatchCustomersUsersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchCustomersUsersIDBadRequest creates a PatchCustomersUsersIDBadRequest with default headers values
func NewPatchCustomersUsersIDBadRequest() *PatchCustomersUsersIDBadRequest {
	return &PatchCustomersUsersIDBadRequest{}
}

/*
PatchCustomersUsersIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PatchCustomersUsersIDBadRequest struct {
	Payload *models.ErrdetailsBadRequest
}

// IsSuccess returns true when this patch customers users Id bad request response has a 2xx status code
func (o *PatchCustomersUsersIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch customers users Id bad request response has a 3xx status code
func (o *PatchCustomersUsersIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch customers users Id bad request response has a 4xx status code
func (o *PatchCustomersUsersIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch customers users Id bad request response has a 5xx status code
func (o *PatchCustomersUsersIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this patch customers users Id bad request response a status code equal to that given
func (o *PatchCustomersUsersIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the patch customers users Id bad request response
func (o *PatchCustomersUsersIDBadRequest) Code() int {
	return 400
}

func (o *PatchCustomersUsersIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/{id}][%d] patchCustomersUsersIdBadRequest %s", 400, payload)
}

func (o *PatchCustomersUsersIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/{id}][%d] patchCustomersUsersIdBadRequest %s", 400, payload)
}

func (o *PatchCustomersUsersIDBadRequest) GetPayload() *models.ErrdetailsBadRequest {
	return o.Payload
}

func (o *PatchCustomersUsersIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrdetailsBadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchCustomersUsersIDInternalServerError creates a PatchCustomersUsersIDInternalServerError with default headers values
func NewPatchCustomersUsersIDInternalServerError() *PatchCustomersUsersIDInternalServerError {
	return &PatchCustomersUsersIDInternalServerError{}
}

/*
PatchCustomersUsersIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PatchCustomersUsersIDInternalServerError struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this patch customers users Id internal server error response has a 2xx status code
func (o *PatchCustomersUsersIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch customers users Id internal server error response has a 3xx status code
func (o *PatchCustomersUsersIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch customers users Id internal server error response has a 4xx status code
func (o *PatchCustomersUsersIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch customers users Id internal server error response has a 5xx status code
func (o *PatchCustomersUsersIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this patch customers users Id internal server error response a status code equal to that given
func (o *PatchCustomersUsersIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the patch customers users Id internal server error response
func (o *PatchCustomersUsersIDInternalServerError) Code() int {
	return 500
}

func (o *PatchCustomersUsersIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/{id}][%d] patchCustomersUsersIdInternalServerError %s", 500, payload)
}

func (o *PatchCustomersUsersIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /customers/users/{id}][%d] patchCustomersUsersIdInternalServerError %s", 500, payload)
}

func (o *PatchCustomersUsersIDInternalServerError) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PatchCustomersUsersIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
