// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// NewPostCustomersSessionRefreshSessionParams creates a new PostCustomersSessionRefreshSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCustomersSessionRefreshSessionParams() *PostCustomersSessionRefreshSessionParams {
	return &PostCustomersSessionRefreshSessionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCustomersSessionRefreshSessionParamsWithTimeout creates a new PostCustomersSessionRefreshSessionParams object
// with the ability to set a timeout on a request.
func NewPostCustomersSessionRefreshSessionParamsWithTimeout(timeout time.Duration) *PostCustomersSessionRefreshSessionParams {
	return &PostCustomersSessionRefreshSessionParams{
		timeout: timeout,
	}
}

// NewPostCustomersSessionRefreshSessionParamsWithContext creates a new PostCustomersSessionRefreshSessionParams object
// with the ability to set a context for a request.
func NewPostCustomersSessionRefreshSessionParamsWithContext(ctx context.Context) *PostCustomersSessionRefreshSessionParams {
	return &PostCustomersSessionRefreshSessionParams{
		Context: ctx,
	}
}

// NewPostCustomersSessionRefreshSessionParamsWithHTTPClient creates a new PostCustomersSessionRefreshSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCustomersSessionRefreshSessionParamsWithHTTPClient(client *http.Client) *PostCustomersSessionRefreshSessionParams {
	return &PostCustomersSessionRefreshSessionParams{
		HTTPClient: client,
	}
}

/*
PostCustomersSessionRefreshSessionParams contains all the parameters to send to the API endpoint

	for the post customers session refresh session operation.

	Typically these are written to a http.Request.
*/
type PostCustomersSessionRefreshSessionParams struct {

	/* XRequestLocale.

	   Locale
	*/
	XRequestLocale *string

	/* Dto.

	   Refresh session dto
	*/
	Dto *models.SessionspbRefreshSessionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post customers session refresh session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCustomersSessionRefreshSessionParams) WithDefaults() *PostCustomersSessionRefreshSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post customers session refresh session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCustomersSessionRefreshSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) WithTimeout(timeout time.Duration) *PostCustomersSessionRefreshSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) WithContext(ctx context.Context) *PostCustomersSessionRefreshSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) WithHTTPClient(client *http.Client) *PostCustomersSessionRefreshSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestLocale adds the xRequestLocale to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) WithXRequestLocale(xRequestLocale *string) *PostCustomersSessionRefreshSessionParams {
	o.SetXRequestLocale(xRequestLocale)
	return o
}

// SetXRequestLocale adds the xRequestLocale to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) SetXRequestLocale(xRequestLocale *string) {
	o.XRequestLocale = xRequestLocale
}

// WithDto adds the dto to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) WithDto(dto *models.SessionspbRefreshSessionRequest) *PostCustomersSessionRefreshSessionParams {
	o.SetDto(dto)
	return o
}

// SetDto adds the dto to the post customers session refresh session params
func (o *PostCustomersSessionRefreshSessionParams) SetDto(dto *models.SessionspbRefreshSessionRequest) {
	o.Dto = dto
}

// WriteToRequest writes these params to a swagger request
func (o *PostCustomersSessionRefreshSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestLocale != nil {

		// header param X-Request-Locale
		if err := r.SetHeaderParam("X-Request-Locale", *o.XRequestLocale); err != nil {
			return err
		}
	}
	if o.Dto != nil {
		if err := r.SetBodyParam(o.Dto); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
