// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// PostCustomersSessionRefreshSessionReader is a Reader for the PostCustomersSessionRefreshSession structure.
type PostCustomersSessionRefreshSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomersSessionRefreshSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostCustomersSessionRefreshSessionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostCustomersSessionRefreshSessionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostCustomersSessionRefreshSessionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /customers/session/refresh-session] PostCustomersSessionRefreshSession", response, response.Code())
	}
}

// NewPostCustomersSessionRefreshSessionCreated creates a PostCustomersSessionRefreshSessionCreated with default headers values
func NewPostCustomersSessionRefreshSessionCreated() *PostCustomersSessionRefreshSessionCreated {
	return &PostCustomersSessionRefreshSessionCreated{}
}

/*
PostCustomersSessionRefreshSessionCreated describes a response with status code 201, with default header values.

Created
*/
type PostCustomersSessionRefreshSessionCreated struct {
	Payload *models.SessionspbCreateSessionResponse
}

// IsSuccess returns true when this post customers session refresh session created response has a 2xx status code
func (o *PostCustomersSessionRefreshSessionCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post customers session refresh session created response has a 3xx status code
func (o *PostCustomersSessionRefreshSessionCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session refresh session created response has a 4xx status code
func (o *PostCustomersSessionRefreshSessionCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post customers session refresh session created response has a 5xx status code
func (o *PostCustomersSessionRefreshSessionCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers session refresh session created response a status code equal to that given
func (o *PostCustomersSessionRefreshSessionCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post customers session refresh session created response
func (o *PostCustomersSessionRefreshSessionCreated) Code() int {
	return 201
}

func (o *PostCustomersSessionRefreshSessionCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/refresh-session][%d] postCustomersSessionRefreshSessionCreated %s", 201, payload)
}

func (o *PostCustomersSessionRefreshSessionCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/refresh-session][%d] postCustomersSessionRefreshSessionCreated %s", 201, payload)
}

func (o *PostCustomersSessionRefreshSessionCreated) GetPayload() *models.SessionspbCreateSessionResponse {
	return o.Payload
}

func (o *PostCustomersSessionRefreshSessionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SessionspbCreateSessionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersSessionRefreshSessionBadRequest creates a PostCustomersSessionRefreshSessionBadRequest with default headers values
func NewPostCustomersSessionRefreshSessionBadRequest() *PostCustomersSessionRefreshSessionBadRequest {
	return &PostCustomersSessionRefreshSessionBadRequest{}
}

/*
PostCustomersSessionRefreshSessionBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostCustomersSessionRefreshSessionBadRequest struct {
	Payload *models.ErrdetailsBadRequest
}

// IsSuccess returns true when this post customers session refresh session bad request response has a 2xx status code
func (o *PostCustomersSessionRefreshSessionBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers session refresh session bad request response has a 3xx status code
func (o *PostCustomersSessionRefreshSessionBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session refresh session bad request response has a 4xx status code
func (o *PostCustomersSessionRefreshSessionBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post customers session refresh session bad request response has a 5xx status code
func (o *PostCustomersSessionRefreshSessionBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers session refresh session bad request response a status code equal to that given
func (o *PostCustomersSessionRefreshSessionBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post customers session refresh session bad request response
func (o *PostCustomersSessionRefreshSessionBadRequest) Code() int {
	return 400
}

func (o *PostCustomersSessionRefreshSessionBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/refresh-session][%d] postCustomersSessionRefreshSessionBadRequest %s", 400, payload)
}

func (o *PostCustomersSessionRefreshSessionBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/refresh-session][%d] postCustomersSessionRefreshSessionBadRequest %s", 400, payload)
}

func (o *PostCustomersSessionRefreshSessionBadRequest) GetPayload() *models.ErrdetailsBadRequest {
	return o.Payload
}

func (o *PostCustomersSessionRefreshSessionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrdetailsBadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersSessionRefreshSessionInternalServerError creates a PostCustomersSessionRefreshSessionInternalServerError with default headers values
func NewPostCustomersSessionRefreshSessionInternalServerError() *PostCustomersSessionRefreshSessionInternalServerError {
	return &PostCustomersSessionRefreshSessionInternalServerError{}
}

/*
PostCustomersSessionRefreshSessionInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostCustomersSessionRefreshSessionInternalServerError struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this post customers session refresh session internal server error response has a 2xx status code
func (o *PostCustomersSessionRefreshSessionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers session refresh session internal server error response has a 3xx status code
func (o *PostCustomersSessionRefreshSessionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session refresh session internal server error response has a 4xx status code
func (o *PostCustomersSessionRefreshSessionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post customers session refresh session internal server error response has a 5xx status code
func (o *PostCustomersSessionRefreshSessionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post customers session refresh session internal server error response a status code equal to that given
func (o *PostCustomersSessionRefreshSessionInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post customers session refresh session internal server error response
func (o *PostCustomersSessionRefreshSessionInternalServerError) Code() int {
	return 500
}

func (o *PostCustomersSessionRefreshSessionInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/refresh-session][%d] postCustomersSessionRefreshSessionInternalServerError %s", 500, payload)
}

func (o *PostCustomersSessionRefreshSessionInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/refresh-session][%d] postCustomersSessionRefreshSessionInternalServerError %s", 500, payload)
}

func (o *PostCustomersSessionRefreshSessionInternalServerError) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PostCustomersSessionRefreshSessionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
