// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// PostCustomersUsersReader is a Reader for the PostCustomersUsers structure.
type PostCustomersUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomersUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostCustomersUsersCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostCustomersUsersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostCustomersUsersForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostCustomersUsersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /customers/users] PostCustomersUsers", response, response.Code())
	}
}

// NewPostCustomersUsersCreated creates a PostCustomersUsersCreated with default headers values
func NewPostCustomersUsersCreated() *PostCustomersUsersCreated {
	return &PostCustomersUsersCreated{}
}

/*
PostCustomersUsersCreated describes a response with status code 201, with default header values.

Created
*/
type PostCustomersUsersCreated struct {
	Payload *models.UserspbCreateUserResponse
}

// IsSuccess returns true when this post customers users created response has a 2xx status code
func (o *PostCustomersUsersCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post customers users created response has a 3xx status code
func (o *PostCustomersUsersCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers users created response has a 4xx status code
func (o *PostCustomersUsersCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post customers users created response has a 5xx status code
func (o *PostCustomersUsersCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers users created response a status code equal to that given
func (o *PostCustomersUsersCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post customers users created response
func (o *PostCustomersUsersCreated) Code() int {
	return 201
}

func (o *PostCustomersUsersCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/users][%d] postCustomersUsersCreated %s", 201, payload)
}

func (o *PostCustomersUsersCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/users][%d] postCustomersUsersCreated %s", 201, payload)
}

func (o *PostCustomersUsersCreated) GetPayload() *models.UserspbCreateUserResponse {
	return o.Payload
}

func (o *PostCustomersUsersCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserspbCreateUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersUsersBadRequest creates a PostCustomersUsersBadRequest with default headers values
func NewPostCustomersUsersBadRequest() *PostCustomersUsersBadRequest {
	return &PostCustomersUsersBadRequest{}
}

/*
PostCustomersUsersBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostCustomersUsersBadRequest struct {
	Payload *models.ErrdetailsBadRequest
}

// IsSuccess returns true when this post customers users bad request response has a 2xx status code
func (o *PostCustomersUsersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers users bad request response has a 3xx status code
func (o *PostCustomersUsersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers users bad request response has a 4xx status code
func (o *PostCustomersUsersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post customers users bad request response has a 5xx status code
func (o *PostCustomersUsersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers users bad request response a status code equal to that given
func (o *PostCustomersUsersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post customers users bad request response
func (o *PostCustomersUsersBadRequest) Code() int {
	return 400
}

func (o *PostCustomersUsersBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/users][%d] postCustomersUsersBadRequest %s", 400, payload)
}

func (o *PostCustomersUsersBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/users][%d] postCustomersUsersBadRequest %s", 400, payload)
}

func (o *PostCustomersUsersBadRequest) GetPayload() *models.ErrdetailsBadRequest {
	return o.Payload
}

func (o *PostCustomersUsersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrdetailsBadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersUsersForbidden creates a PostCustomersUsersForbidden with default headers values
func NewPostCustomersUsersForbidden() *PostCustomersUsersForbidden {
	return &PostCustomersUsersForbidden{}
}

/*
PostCustomersUsersForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostCustomersUsersForbidden struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this post customers users forbidden response has a 2xx status code
func (o *PostCustomersUsersForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers users forbidden response has a 3xx status code
func (o *PostCustomersUsersForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers users forbidden response has a 4xx status code
func (o *PostCustomersUsersForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post customers users forbidden response has a 5xx status code
func (o *PostCustomersUsersForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers users forbidden response a status code equal to that given
func (o *PostCustomersUsersForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post customers users forbidden response
func (o *PostCustomersUsersForbidden) Code() int {
	return 403
}

func (o *PostCustomersUsersForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/users][%d] postCustomersUsersForbidden %s", 403, payload)
}

func (o *PostCustomersUsersForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/users][%d] postCustomersUsersForbidden %s", 403, payload)
}

func (o *PostCustomersUsersForbidden) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PostCustomersUsersForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersUsersInternalServerError creates a PostCustomersUsersInternalServerError with default headers values
func NewPostCustomersUsersInternalServerError() *PostCustomersUsersInternalServerError {
	return &PostCustomersUsersInternalServerError{}
}

/*
PostCustomersUsersInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostCustomersUsersInternalServerError struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this post customers users internal server error response has a 2xx status code
func (o *PostCustomersUsersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers users internal server error response has a 3xx status code
func (o *PostCustomersUsersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers users internal server error response has a 4xx status code
func (o *PostCustomersUsersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post customers users internal server error response has a 5xx status code
func (o *PostCustomersUsersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post customers users internal server error response a status code equal to that given
func (o *PostCustomersUsersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post customers users internal server error response
func (o *PostCustomersUsersInternalServerError) Code() int {
	return 500
}

func (o *PostCustomersUsersInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/users][%d] postCustomersUsersInternalServerError %s", 500, payload)
}

func (o *PostCustomersUsersInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/users][%d] postCustomersUsersInternalServerError %s", 500, payload)
}

func (o *PostCustomersUsersInternalServerError) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PostCustomersUsersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
