// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// PostCustomersSessionLoginReader is a Reader for the PostCustomersSessionLogin structure.
type PostCustomersSessionLoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomersSessionLoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostCustomersSessionLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 228:
		result := NewPostCustomersSessionLoginStatus228()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostCustomersSessionLoginBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostCustomersSessionLoginUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostCustomersSessionLoginForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostCustomersSessionLoginNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostCustomersSessionLoginInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /customers/session/login] PostCustomersSessionLogin", response, response.Code())
	}
}

// NewPostCustomersSessionLoginOK creates a PostCustomersSessionLoginOK with default headers values
func NewPostCustomersSessionLoginOK() *PostCustomersSessionLoginOK {
	return &PostCustomersSessionLoginOK{}
}

/*
PostCustomersSessionLoginOK describes a response with status code 200, with default header values.

OK
*/
type PostCustomersSessionLoginOK struct {
	Payload *models.SessionspbCreateSessionResponse
}

// IsSuccess returns true when this post customers session login o k response has a 2xx status code
func (o *PostCustomersSessionLoginOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post customers session login o k response has a 3xx status code
func (o *PostCustomersSessionLoginOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session login o k response has a 4xx status code
func (o *PostCustomersSessionLoginOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post customers session login o k response has a 5xx status code
func (o *PostCustomersSessionLoginOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers session login o k response a status code equal to that given
func (o *PostCustomersSessionLoginOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post customers session login o k response
func (o *PostCustomersSessionLoginOK) Code() int {
	return 200
}

func (o *PostCustomersSessionLoginOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginOK %s", 200, payload)
}

func (o *PostCustomersSessionLoginOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginOK %s", 200, payload)
}

func (o *PostCustomersSessionLoginOK) GetPayload() *models.SessionspbCreateSessionResponse {
	return o.Payload
}

func (o *PostCustomersSessionLoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SessionspbCreateSessionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersSessionLoginStatus228 creates a PostCustomersSessionLoginStatus228 with default headers values
func NewPostCustomersSessionLoginStatus228() *PostCustomersSessionLoginStatus228 {
	return &PostCustomersSessionLoginStatus228{}
}

/*
PostCustomersSessionLoginStatus228 describes a response with status code 228, with default header values.

PostCustomersSessionLoginStatus228 post customers session login status228
*/
type PostCustomersSessionLoginStatus228 struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this post customers session login status228 response has a 2xx status code
func (o *PostCustomersSessionLoginStatus228) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post customers session login status228 response has a 3xx status code
func (o *PostCustomersSessionLoginStatus228) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session login status228 response has a 4xx status code
func (o *PostCustomersSessionLoginStatus228) IsClientError() bool {
	return false
}

// IsServerError returns true when this post customers session login status228 response has a 5xx status code
func (o *PostCustomersSessionLoginStatus228) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers session login status228 response a status code equal to that given
func (o *PostCustomersSessionLoginStatus228) IsCode(code int) bool {
	return code == 228
}

// Code gets the status code for the post customers session login status228 response
func (o *PostCustomersSessionLoginStatus228) Code() int {
	return 228
}

func (o *PostCustomersSessionLoginStatus228) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginStatus228 %s", 228, payload)
}

func (o *PostCustomersSessionLoginStatus228) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginStatus228 %s", 228, payload)
}

func (o *PostCustomersSessionLoginStatus228) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PostCustomersSessionLoginStatus228) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersSessionLoginBadRequest creates a PostCustomersSessionLoginBadRequest with default headers values
func NewPostCustomersSessionLoginBadRequest() *PostCustomersSessionLoginBadRequest {
	return &PostCustomersSessionLoginBadRequest{}
}

/*
PostCustomersSessionLoginBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostCustomersSessionLoginBadRequest struct {
	Payload *models.ErrdetailsBadRequest
}

// IsSuccess returns true when this post customers session login bad request response has a 2xx status code
func (o *PostCustomersSessionLoginBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers session login bad request response has a 3xx status code
func (o *PostCustomersSessionLoginBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session login bad request response has a 4xx status code
func (o *PostCustomersSessionLoginBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post customers session login bad request response has a 5xx status code
func (o *PostCustomersSessionLoginBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers session login bad request response a status code equal to that given
func (o *PostCustomersSessionLoginBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post customers session login bad request response
func (o *PostCustomersSessionLoginBadRequest) Code() int {
	return 400
}

func (o *PostCustomersSessionLoginBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginBadRequest %s", 400, payload)
}

func (o *PostCustomersSessionLoginBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginBadRequest %s", 400, payload)
}

func (o *PostCustomersSessionLoginBadRequest) GetPayload() *models.ErrdetailsBadRequest {
	return o.Payload
}

func (o *PostCustomersSessionLoginBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrdetailsBadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersSessionLoginUnauthorized creates a PostCustomersSessionLoginUnauthorized with default headers values
func NewPostCustomersSessionLoginUnauthorized() *PostCustomersSessionLoginUnauthorized {
	return &PostCustomersSessionLoginUnauthorized{}
}

/*
PostCustomersSessionLoginUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostCustomersSessionLoginUnauthorized struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this post customers session login unauthorized response has a 2xx status code
func (o *PostCustomersSessionLoginUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers session login unauthorized response has a 3xx status code
func (o *PostCustomersSessionLoginUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session login unauthorized response has a 4xx status code
func (o *PostCustomersSessionLoginUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post customers session login unauthorized response has a 5xx status code
func (o *PostCustomersSessionLoginUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers session login unauthorized response a status code equal to that given
func (o *PostCustomersSessionLoginUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post customers session login unauthorized response
func (o *PostCustomersSessionLoginUnauthorized) Code() int {
	return 401
}

func (o *PostCustomersSessionLoginUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginUnauthorized %s", 401, payload)
}

func (o *PostCustomersSessionLoginUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginUnauthorized %s", 401, payload)
}

func (o *PostCustomersSessionLoginUnauthorized) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PostCustomersSessionLoginUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersSessionLoginForbidden creates a PostCustomersSessionLoginForbidden with default headers values
func NewPostCustomersSessionLoginForbidden() *PostCustomersSessionLoginForbidden {
	return &PostCustomersSessionLoginForbidden{}
}

/*
PostCustomersSessionLoginForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostCustomersSessionLoginForbidden struct {
	Payload *models.UserspbUserSessionActionResponse
}

// IsSuccess returns true when this post customers session login forbidden response has a 2xx status code
func (o *PostCustomersSessionLoginForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers session login forbidden response has a 3xx status code
func (o *PostCustomersSessionLoginForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session login forbidden response has a 4xx status code
func (o *PostCustomersSessionLoginForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post customers session login forbidden response has a 5xx status code
func (o *PostCustomersSessionLoginForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers session login forbidden response a status code equal to that given
func (o *PostCustomersSessionLoginForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post customers session login forbidden response
func (o *PostCustomersSessionLoginForbidden) Code() int {
	return 403
}

func (o *PostCustomersSessionLoginForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginForbidden %s", 403, payload)
}

func (o *PostCustomersSessionLoginForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginForbidden %s", 403, payload)
}

func (o *PostCustomersSessionLoginForbidden) GetPayload() *models.UserspbUserSessionActionResponse {
	return o.Payload
}

func (o *PostCustomersSessionLoginForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserspbUserSessionActionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersSessionLoginNotFound creates a PostCustomersSessionLoginNotFound with default headers values
func NewPostCustomersSessionLoginNotFound() *PostCustomersSessionLoginNotFound {
	return &PostCustomersSessionLoginNotFound{}
}

/*
PostCustomersSessionLoginNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostCustomersSessionLoginNotFound struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this post customers session login not found response has a 2xx status code
func (o *PostCustomersSessionLoginNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers session login not found response has a 3xx status code
func (o *PostCustomersSessionLoginNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session login not found response has a 4xx status code
func (o *PostCustomersSessionLoginNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post customers session login not found response has a 5xx status code
func (o *PostCustomersSessionLoginNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post customers session login not found response a status code equal to that given
func (o *PostCustomersSessionLoginNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post customers session login not found response
func (o *PostCustomersSessionLoginNotFound) Code() int {
	return 404
}

func (o *PostCustomersSessionLoginNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginNotFound %s", 404, payload)
}

func (o *PostCustomersSessionLoginNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginNotFound %s", 404, payload)
}

func (o *PostCustomersSessionLoginNotFound) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PostCustomersSessionLoginNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostCustomersSessionLoginInternalServerError creates a PostCustomersSessionLoginInternalServerError with default headers values
func NewPostCustomersSessionLoginInternalServerError() *PostCustomersSessionLoginInternalServerError {
	return &PostCustomersSessionLoginInternalServerError{}
}

/*
PostCustomersSessionLoginInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostCustomersSessionLoginInternalServerError struct {
	Payload *models.HttputilsErrorResponse
}

// IsSuccess returns true when this post customers session login internal server error response has a 2xx status code
func (o *PostCustomersSessionLoginInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post customers session login internal server error response has a 3xx status code
func (o *PostCustomersSessionLoginInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post customers session login internal server error response has a 4xx status code
func (o *PostCustomersSessionLoginInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post customers session login internal server error response has a 5xx status code
func (o *PostCustomersSessionLoginInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post customers session login internal server error response a status code equal to that given
func (o *PostCustomersSessionLoginInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post customers session login internal server error response
func (o *PostCustomersSessionLoginInternalServerError) Code() int {
	return 500
}

func (o *PostCustomersSessionLoginInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginInternalServerError %s", 500, payload)
}

func (o *PostCustomersSessionLoginInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /customers/session/login][%d] postCustomersSessionLoginInternalServerError %s", 500, payload)
}

func (o *PostCustomersSessionLoginInternalServerError) GetPayload() *models.HttputilsErrorResponse {
	return o.Payload
}

func (o *PostCustomersSessionLoginInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttputilsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
