// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// NewPostCustomersSessionLoginParams creates a new PostCustomersSessionLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCustomersSessionLoginParams() *PostCustomersSessionLoginParams {
	return &PostCustomersSessionLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCustomersSessionLoginParamsWithTimeout creates a new PostCustomersSessionLoginParams object
// with the ability to set a timeout on a request.
func NewPostCustomersSessionLoginParamsWithTimeout(timeout time.Duration) *PostCustomersSessionLoginParams {
	return &PostCustomersSessionLoginParams{
		timeout: timeout,
	}
}

// NewPostCustomersSessionLoginParamsWithContext creates a new PostCustomersSessionLoginParams object
// with the ability to set a context for a request.
func NewPostCustomersSessionLoginParamsWithContext(ctx context.Context) *PostCustomersSessionLoginParams {
	return &PostCustomersSessionLoginParams{
		Context: ctx,
	}
}

// NewPostCustomersSessionLoginParamsWithHTTPClient creates a new PostCustomersSessionLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCustomersSessionLoginParamsWithHTTPClient(client *http.Client) *PostCustomersSessionLoginParams {
	return &PostCustomersSessionLoginParams{
		HTTPClient: client,
	}
}

/*
PostCustomersSessionLoginParams contains all the parameters to send to the API endpoint

	for the post customers session login operation.

	Typically these are written to a http.Request.
*/
type PostCustomersSessionLoginParams struct {

	/* XRequestLocale.

	   Locale
	*/
	XRequestLocale *string

	/* Dto.

	   Dto for login in account
	*/
	Dto *models.GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post customers session login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCustomersSessionLoginParams) WithDefaults() *PostCustomersSessionLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post customers session login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCustomersSessionLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post customers session login params
func (o *PostCustomersSessionLoginParams) WithTimeout(timeout time.Duration) *PostCustomersSessionLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post customers session login params
func (o *PostCustomersSessionLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post customers session login params
func (o *PostCustomersSessionLoginParams) WithContext(ctx context.Context) *PostCustomersSessionLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post customers session login params
func (o *PostCustomersSessionLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post customers session login params
func (o *PostCustomersSessionLoginParams) WithHTTPClient(client *http.Client) *PostCustomersSessionLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post customers session login params
func (o *PostCustomersSessionLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestLocale adds the xRequestLocale to the post customers session login params
func (o *PostCustomersSessionLoginParams) WithXRequestLocale(xRequestLocale *string) *PostCustomersSessionLoginParams {
	o.SetXRequestLocale(xRequestLocale)
	return o
}

// SetXRequestLocale adds the xRequestLocale to the post customers session login params
func (o *PostCustomersSessionLoginParams) SetXRequestLocale(xRequestLocale *string) {
	o.XRequestLocale = xRequestLocale
}

// WithDto adds the dto to the post customers session login params
func (o *PostCustomersSessionLoginParams) WithDto(dto *models.GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) *PostCustomersSessionLoginParams {
	o.SetDto(dto)
	return o
}

// SetDto adds the dto to the post customers session login params
func (o *PostCustomersSessionLoginParams) SetDto(dto *models.GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) {
	o.Dto = dto
}

// WriteToRequest writes these params to a swagger request
func (o *PostCustomersSessionLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestLocale != nil {

		// header param X-Request-Locale
		if err := r.SetHeaderParam("X-Request-Locale", *o.XRequestLocale); err != nil {
			return err
		}
	}
	if o.Dto != nil {
		if err := r.SetBodyParam(o.Dto); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
