// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Fedotv Maxim (developer)",
            "email": "f3d0t0tvmax@yandex.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customers/users": {
            "post": {
                "description": "Create new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Create user account",
                "parameters": [
                    {
                        "description": "Create user account with body dto",
                        "name": "dto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userspb.CreateUserRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Locale",
                        "name": "X-Request-Locale",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/userspb.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errdetails.BadRequest"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customers/users/{id}": {
            "get": {
                "description": "Get user base info by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Get user base info by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id parameter",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Locale",
                        "name": "X-Request-Locale",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userspb.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errdetails.BadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id parameter",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update user profile with body dto",
                        "name": "dto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userspb.UpdateUserProfileData"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Locale",
                        "name": "X-Request-Locale",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errdetails.BadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errdetails.BadRequest": {
            "type": "object",
            "properties": {
                "field_violations": {
                    "description": "Describes all violations in a client request.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/errdetails.BadRequest_FieldViolation"
                    }
                }
            }
        },
        "errdetails.BadRequest_FieldViolation": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "A description of why the request element is bad.",
                    "type": "string"
                },
                "field": {
                    "description": "A path that leads to a field in the request body. The value will be a\nsequence of dot-separated identifiers that identify a protocol buffer\nfield.\n\nConsider the following:\n\n\tmessage CreateContactRequest {\n\t  message EmailAddress {\n\t    enum Type {\n\t      TYPE_UNSPECIFIED = 0;\n\t      HOME = 1;\n\t      WORK = 2;\n\t    }\n\n\t    optional string email = 1;\n\t    repeated EmailType type = 2;\n\t  }\n\n\t  string full_name = 1;\n\t  repeated EmailAddress email_addresses = 2;\n\t}\n\nIn this example, in proto ` + "`" + `field` + "`" + ` could take one of the following values:\n\n  - ` + "`" + `full_name` + "`" + ` for a violation in the ` + "`" + `full_name` + "`" + ` value\n  - ` + "`" + `email_addresses[1].email` + "`" + ` for a violation in the ` + "`" + `email` + "`" + ` field of the\n    first ` + "`" + `email_addresses` + "`" + ` message\n  - ` + "`" + `email_addresses[3].type[2]` + "`" + ` for a violation in the second ` + "`" + `type` + "`" + `\n    value in the third ` + "`" + `email_addresses` + "`" + ` message.\n\nIn JSON, the same values are represented as:\n\n  - ` + "`" + `fullName` + "`" + ` for a violation in the ` + "`" + `fullName` + "`" + ` value\n  - ` + "`" + `emailAddresses[1].email` + "`" + ` for a violation in the ` + "`" + `email` + "`" + ` field of the\n    first ` + "`" + `emailAddresses` + "`" + ` message\n  - ` + "`" + `emailAddresses[3].type[2]` + "`" + ` for a violation in the second ` + "`" + `type` + "`" + `\n    value in the third ` + "`" + `emailAddresses` + "`" + ` message.",
                    "type": "string"
                },
                "localized_message": {
                    "description": "Provides a localized error message for field-level errors that is safe to\nreturn to the API consumer.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/errdetails.LocalizedMessage"
                        }
                    ]
                },
                "reason": {
                    "description": "The reason of the field-level error. This is a constant value that\nidentifies the proximate cause of the field-level error. It should\nuniquely identify the type of the FieldViolation within the scope of the\ngoogle.rpc.ErrorInfo.domain. This should be at most 63\ncharacters and match a regular expression of ` + "`" + `[A-Z][A-Z0-9_]+[A-Z0-9]` + "`" + `,\nwhich represents UPPER_SNAKE_CASE.",
                    "type": "string"
                }
            }
        },
        "errdetails.LocalizedMessage": {
            "type": "object",
            "properties": {
                "locale": {
                    "description": "The locale used following the specification defined at\nhttps://www.rfc-editor.org/rfc/bcp/bcp47.txt.\nExamples are: \"en-US\", \"fr-CH\", \"es-MX\"",
                    "type": "string"
                },
                "message": {
                    "description": "The localized error message in the above locale.",
                    "type": "string"
                }
            }
        },
        "httputils.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "timestamppb.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "description": "Non-negative fractions of a second at nanosecond resolution. This field is\nthe nanosecond portion of the duration, not an alternative to seconds.\nNegative second values with fractions must still have non-negative nanos\nvalues that count forward in time. Must be between 0 and 999,999,999\ninclusive.",
                    "type": "integer"
                },
                "seconds": {
                    "description": "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must\nbe between -315576000000 and 315576000000 inclusive (which corresponds to\n0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z).",
                    "type": "integer"
                }
            }
        },
        "userspb.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "makc-dgek@mail.ru"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "userspb.CreateUserResponse": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "userspb.GenderValue": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "GenderValue_GENDER_UNSPECIFIED",
                "GenderValue_GENDER_UNSELECTED",
                "GenderValue_GENDER_MALE",
                "GenderValue_GENDER_FEMALE"
            ]
        },
        "userspb.Profile": {
            "type": "object",
            "required": [
                "gender",
                "updated_at"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "format": "url",
                    "example": "https://example.com/photo.jpg"
                },
                "birth_date": {
                    "type": "string",
                    "example": "2001-11-23"
                },
                "first_name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "gender": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/userspb.GenderValue"
                        }
                    ],
                    "example": 1
                },
                "last_name": {
                    "type": "string",
                    "example": "Ivanov"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Olegovich"
                },
                "updated_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                }
            }
        },
        "userspb.UpdateUserProfileData": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "format": "url",
                    "example": "https://example.com/photo.jpg"
                },
                "birth_date": {
                    "type": "string",
                    "example": "2001-11-23"
                },
                "first_name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "gender_value": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/userspb.GenderValue"
                        }
                    ],
                    "example": 1
                },
                "last_name": {
                    "type": "string",
                    "example": "Ivanov"
                },
                "middle_name": {
                    "type": "string",
                    "example": "Olegovich"
                }
            }
        },
        "userspb.User": {
            "type": "object",
            "required": [
                "created_at",
                "email",
                "id",
                "updated_at"
            ],
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "makc-dgek@mail.ru"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "phone": {
                    "type": "string",
                    "example": "+79517735133"
                },
                "profile": {
                    "$ref": "#/definitions/userspb.Profile"
                },
                "updated_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Documentation for microservices shop API Gateway",
	Description:      "Swagger Documentation for API Gateway of microservices shop project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
