package icon

type ID string

const (
	IconAngry ID = "icon-angry"
	IconCalendar ID = "icon-calendar"
	IconCheck ID = "icon-check"
	IconChevronDown ID = "icon-chevron_down"
	IconChevronLeft ID = "icon-chevron_left"
	IconChevronRight ID = "icon-chevron_right"
	IconChevronUp ID = "icon-chevron_up"
	IconChevronsUpDown ID = "icon-chevrons_up_down"
	IconCircleCheck ID = "icon-circle_check"
	IconCircleQuestionMark ID = "icon-circle_question_mark"
	IconCircleUserRound ID = "icon-circle_user_round"
	IconCircleX ID = "icon-circle_x"
	IconClipboard ID = "icon-clipboard"
	IconClock ID = "icon-clock"
	IconCode ID = "icon-code"
	IconEllipsis ID = "icon-ellipsis"
	IconEye ID = "icon-eye"
	IconEyeOff ID = "icon-eye_off"
	IconFile ID = "icon-file"
	IconFileText ID = "icon-file_text"
	IconFolder ID = "icon-folder"
	IconFrown ID = "icon-frown"
	IconGear ID = "icon-gear"
	IconGithub ID = "icon-github"
	IconHeart ID = "icon-heart"
	IconHouse ID = "icon-house"
	IconInbox ID = "icon-inbox"
	IconInfo ID = "icon-info"
	IconLaugh ID = "icon-laugh"
	IconLifeBuoy ID = "icon-life-buoy"
	IconLockKeyhole ID = "icon-lock_keyhole"
	IconLockKeyholeOpen ID = "icon-lock_keyhole_open"
	IconLogout ID = "icon-logout"
	IconMail ID = "icon-mail"
	IconMeh ID = "icon-meh"
	IconMessageCircle ID = "icon-message_circle"
	IconMessageSquare ID = "icon-message_square"
	IconMinus ID = "icon-minus"
	IconPanelLeft ID = "icon-panel_left"
	IconSearch ID = "icon-search"
	IconSend ID = "icon-send"
	IconSendHorizontal ID = "icon-send-horizontal"
	IconSmile ID = "icon-smile"
	IconStar ID = "icon-star"
	IconTriangleAlert ID = "icon-triangle_alert"
	IconUserRoundCheck ID = "icon-user_round_check"
	IconUserRoundPlus ID = "icon-user_round_plus"
	IconUserRoundX ID = "icon-user_round_x"
	IconUsers ID = "icon-users"
	IconX ID = "icon-x"
)
