// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fedotovmax/microservices-shop/customer-site/internal/models"
)

// NewPostCustomersUsersParams creates a new PostCustomersUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCustomersUsersParams() *PostCustomersUsersParams {
	return &PostCustomersUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCustomersUsersParamsWithTimeout creates a new PostCustomersUsersParams object
// with the ability to set a timeout on a request.
func NewPostCustomersUsersParamsWithTimeout(timeout time.Duration) *PostCustomersUsersParams {
	return &PostCustomersUsersParams{
		timeout: timeout,
	}
}

// NewPostCustomersUsersParamsWithContext creates a new PostCustomersUsersParams object
// with the ability to set a context for a request.
func NewPostCustomersUsersParamsWithContext(ctx context.Context) *PostCustomersUsersParams {
	return &PostCustomersUsersParams{
		Context: ctx,
	}
}

// NewPostCustomersUsersParamsWithHTTPClient creates a new PostCustomersUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCustomersUsersParamsWithHTTPClient(client *http.Client) *PostCustomersUsersParams {
	return &PostCustomersUsersParams{
		HTTPClient: client,
	}
}

/*
PostCustomersUsersParams contains all the parameters to send to the API endpoint

	for the post customers users operation.

	Typically these are written to a http.Request.
*/
type PostCustomersUsersParams struct {

	/* Dto.

	   Create user account with body dto
	*/
	Dto *models.UserspbCreateUserRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post customers users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCustomersUsersParams) WithDefaults() *PostCustomersUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post customers users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCustomersUsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post customers users params
func (o *PostCustomersUsersParams) WithTimeout(timeout time.Duration) *PostCustomersUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post customers users params
func (o *PostCustomersUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post customers users params
func (o *PostCustomersUsersParams) WithContext(ctx context.Context) *PostCustomersUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post customers users params
func (o *PostCustomersUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post customers users params
func (o *PostCustomersUsersParams) WithHTTPClient(client *http.Client) *PostCustomersUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post customers users params
func (o *PostCustomersUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDto adds the dto to the post customers users params
func (o *PostCustomersUsersParams) WithDto(dto *models.UserspbCreateUserRequest) *PostCustomersUsersParams {
	o.SetDto(dto)
	return o
}

// SetDto adds the dto to the post customers users params
func (o *PostCustomersUsersParams) SetDto(dto *models.UserspbCreateUserRequest) {
	o.Dto = dto
}

// WriteToRequest writes these params to a swagger request
func (o *PostCustomersUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Dto != nil {
		if err := r.SetBodyParam(o.Dto); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
