// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrdetailsLocalizedMessage errdetails localized message
//
// swagger:model errdetails.LocalizedMessage
type ErrdetailsLocalizedMessage struct {

	// The locale used following the specification defined at
	// https://www.rfc-editor.org/rfc/bcp/bcp47.txt.
	// Examples are: "en-US", "fr-CH", "es-MX"
	Locale string `json:"locale,omitempty"`

	// The localized error message in the above locale.
	Message string `json:"message,omitempty"`
}

// Validate validates this errdetails localized message
func (m *ErrdetailsLocalizedMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this errdetails localized message based on context it is used
func (m *ErrdetailsLocalizedMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrdetailsLocalizedMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrdetailsLocalizedMessage) UnmarshalBinary(b []byte) error {
	var res ErrdetailsLocalizedMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
