// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrdetailsBadRequest errdetails bad request
//
// swagger:model errdetails.BadRequest
type ErrdetailsBadRequest struct {

	// Describes all violations in a client request.
	FieldViolations []*ErrdetailsBadRequestFieldViolation `json:"field_violations"`
}

// Validate validates this errdetails bad request
func (m *ErrdetailsBadRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFieldViolations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrdetailsBadRequest) validateFieldViolations(formats strfmt.Registry) error {
	if swag.IsZero(m.FieldViolations) { // not required
		return nil
	}

	for i := 0; i < len(m.FieldViolations); i++ {
		if swag.IsZero(m.FieldViolations[i]) { // not required
			continue
		}

		if m.FieldViolations[i] != nil {
			if err := m.FieldViolations[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("field_violations" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("field_violations" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this errdetails bad request based on the context it is used
func (m *ErrdetailsBadRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFieldViolations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrdetailsBadRequest) contextValidateFieldViolations(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.FieldViolations); i++ {

		if m.FieldViolations[i] != nil {

			if swag.IsZero(m.FieldViolations[i]) { // not required
				return nil
			}

			if err := m.FieldViolations[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("field_violations" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("field_violations" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ErrdetailsBadRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrdetailsBadRequest) UnmarshalBinary(b []byte) error {
	var res ErrdetailsBadRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
