// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ErrdetailsBadRequestFieldViolation errdetails bad request field violation
//
// swagger:model errdetails.BadRequest_FieldViolation
type ErrdetailsBadRequestFieldViolation struct {

	// A description of why the request element is bad.
	Description string `json:"description,omitempty"`

	// A path that leads to a field in the request body. The value will be a
	// sequence of dot-separated identifiers that identify a protocol buffer
	// field.
	//
	// Consider the following:
	//
	// 	message CreateContactRequest {
	// 	  message EmailAddress {
	// 	    enum Type {
	// 	      TYPE_UNSPECIFIED = 0;
	// 	      HOME = 1;
	// 	      WORK = 2;
	// 	    }
	//
	// 	    optional string email = 1;
	// 	    repeated EmailType type = 2;
	// 	  }
	//
	// 	  string full_name = 1;
	// 	  repeated EmailAddress email_addresses = 2;
	// 	}
	//
	// In this example, in proto `field` could take one of the following values:
	//
	//   - `full_name` for a violation in the `full_name` value
	//   - `email_addresses[1].email` for a violation in the `email` field of the
	//     first `email_addresses` message
	//   - `email_addresses[3].type[2]` for a violation in the second `type`
	//     value in the third `email_addresses` message.
	//
	// In JSON, the same values are represented as:
	//
	//   - `fullName` for a violation in the `fullName` value
	//   - `emailAddresses[1].email` for a violation in the `email` field of the
	//     first `emailAddresses` message
	//   - `emailAddresses[3].type[2]` for a violation in the second `type`
	//     value in the third `emailAddresses` message.
	Field string `json:"field,omitempty"`

	// Provides a localized error message for field-level errors that is safe to
	// return to the API consumer.
	LocalizedMessage struct {
		ErrdetailsLocalizedMessage
	} `json:"localized_message,omitempty"`

	// The reason of the field-level error. This is a constant value that
	// identifies the proximate cause of the field-level error. It should
	// uniquely identify the type of the FieldViolation within the scope of the
	// google.rpc.ErrorInfo.domain. This should be at most 63
	// characters and match a regular expression of `[A-Z][A-Z0-9_]+[A-Z0-9]`,
	// which represents UPPER_SNAKE_CASE.
	Reason string `json:"reason,omitempty"`
}

// Validate validates this errdetails bad request field violation
func (m *ErrdetailsBadRequestFieldViolation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocalizedMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrdetailsBadRequestFieldViolation) validateLocalizedMessage(formats strfmt.Registry) error {
	if swag.IsZero(m.LocalizedMessage) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this errdetails bad request field violation based on the context it is used
func (m *ErrdetailsBadRequestFieldViolation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLocalizedMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrdetailsBadRequestFieldViolation) contextValidateLocalizedMessage(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *ErrdetailsBadRequestFieldViolation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrdetailsBadRequestFieldViolation) UnmarshalBinary(b []byte) error {
	var res ErrdetailsBadRequestFieldViolation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
