// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput github com fedotovmax microservices shop api gateway internal domain login input
//
// swagger:model github_com_fedotovmax_microservices-shop_api-gateway_internal_domain.LoginInput
type GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput struct {

	// bypass code
	// Example: 1A2B3C4D5E6F
	BypassCode string `json:"bypass_code,omitempty"`

	// device trust token
	// Example: skdjfsdfsdifsdfsdf123
	DeviceTrustToken string `json:"device_trust_token,omitempty"`

	// email
	// Example: makc-dgek@mail.ru
	// Required: true
	// Format: email
	Email *strfmt.Email `json:"email"`

	// ip
	// Example: 19.56.186.122
	// Required: true
	IP *string `json:"ip"`

	// password
	// Required: true
	Password *string `json:"password"`

	// user agent
	// Example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
	// Required: true
	UserAgent *string `json:"user_agent"`
}

// Validate validates this github com fedotovmax microservices shop api gateway internal domain login input
func (m *GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIP(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserAgent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	if err := validate.FormatOf("email", "body", "email", m.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("ip", "body", m.IP); err != nil {
		return err
	}

	return nil
}

func (m *GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

func (m *GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) validateUserAgent(formats strfmt.Registry) error {

	if err := validate.Required("user_agent", "body", m.UserAgent); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this github com fedotovmax microservices shop api gateway internal domain login input based on context it is used
func (m *GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput) UnmarshalBinary(b []byte) error {
	var res GithubComFedotovmaxMicroservicesShopAPIGatewayInternalDomainLoginInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
