// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SessionspbCreateSessionResponse sessionspb create session response
//
// swagger:model sessionspb.CreateSessionResponse
type SessionspbCreateSessionResponse struct {

	// Types that are valid to be assigned to Payload:
	//
	// 	*CreateSessionResponse_SessionCreated
	// 	*CreateSessionResponse_UserInBlacklist
	// 	*CreateSessionResponse_BadBypassCode
	// 	*CreateSessionResponse_LoginFromNewDevice
	Payload any `json:"payload,omitempty"`
}

// Validate validates this sessionspb create session response
func (m *SessionspbCreateSessionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sessionspb create session response based on context it is used
func (m *SessionspbCreateSessionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SessionspbCreateSessionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SessionspbCreateSessionResponse) UnmarshalBinary(b []byte) error {
	var res SessionspbCreateSessionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
