// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TimestamppbTimestamp timestamppb timestamp
//
// swagger:model timestamppb.Timestamp
type TimestamppbTimestamp struct {

	// Non-negative fractions of a second at nanosecond resolution. This field is
	// the nanosecond portion of the duration, not an alternative to seconds.
	// Negative second values with fractions must still have non-negative nanos
	// values that count forward in time. Must be between 0 and 999,999,999
	// inclusive.
	Nanos int64 `json:"nanos,omitempty"`

	// Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must
	// be between -315576000000 and 315576000000 inclusive (which corresponds to
	// 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z).
	Seconds int64 `json:"seconds,omitempty"`
}

// Validate validates this timestamppb timestamp
func (m *TimestamppbTimestamp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this timestamppb timestamp based on context it is used
func (m *TimestamppbTimestamp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TimestamppbTimestamp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TimestamppbTimestamp) UnmarshalBinary(b []byte) error {
	var res TimestamppbTimestamp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
