// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserspbProfile userspb profile
//
// swagger:model userspb.Profile
type UserspbProfile struct {

	// avatar url
	// Example: https://example.com/photo.jpg
	AvatarURL string `json:"avatar_url,omitempty"`

	// birth date
	// Example: 2001-11-23
	BirthDate string `json:"birth_date,omitempty"`

	// first name
	// Example: Ivan
	FirstName string `json:"first_name,omitempty"`

	// gender
	// Example: 1
	// Required: true
	Gender struct {
		UserspbGenderValue
	} `json:"gender"`

	// last name
	// Example: Ivanov
	LastName string `json:"last_name,omitempty"`

	// middle name
	// Example: Olegovich
	MiddleName string `json:"middle_name,omitempty"`

	// updated at
	// Required: true
	UpdatedAt *TimestamppbTimestamp `json:"updated_at"`
}

// Validate validates this userspb profile
func (m *UserspbProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGender(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserspbProfile) validateGender(formats strfmt.Registry) error {

	return nil
}

func (m *UserspbProfile) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("updated_at", "body", m.UpdatedAt); err != nil {
		return err
	}

	if m.UpdatedAt != nil {
		if err := m.UpdatedAt.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("updated_at")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("updated_at")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this userspb profile based on the context it is used
func (m *UserspbProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGender(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserspbProfile) contextValidateGender(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *UserspbProfile) contextValidateUpdatedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.UpdatedAt != nil {

		if err := m.UpdatedAt.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("updated_at")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("updated_at")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserspbProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserspbProfile) UnmarshalBinary(b []byte) error {
	var res UserspbProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
