// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserspbUserSessionActionResponse userspb user session action response
//
// swagger:model userspb.UserSessionActionResponse
type UserspbUserSessionActionResponse struct {

	// Types that are valid to be assigned to Payload:
	//
	// 	*UserSessionActionResponse_Deleted
	// 	*UserSessionActionResponse_EmailNotVerified
	// 	*UserSessionActionResponse_BadCredentials
	// 	*UserSessionActionResponse_Ok
	Payload any `json:"payload,omitempty"`
}

// Validate validates this userspb user session action response
func (m *UserspbUserSessionActionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this userspb user session action response based on context it is used
func (m *UserspbUserSessionActionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserspbUserSessionActionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserspbUserSessionActionResponse) UnmarshalBinary(b []byte) error {
	var res UserspbUserSessionActionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
