// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// UserspbGenderValue userspb gender value
//
// swagger:model userspb.GenderValue
type UserspbGenderValue int32

// for schema
var userspbGenderValueEnum []any

func init() {
	var res []UserspbGenderValue
	if err := json.Unmarshal([]byte(`[0,1,2,3]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userspbGenderValueEnum = append(userspbGenderValueEnum, v)
	}
}

func (m UserspbGenderValue) validateUserspbGenderValueEnum(path, location string, value UserspbGenderValue) error {
	if err := validate.EnumCase(path, location, value, userspbGenderValueEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this userspb gender value
func (m UserspbGenderValue) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateUserspbGenderValueEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this userspb gender value based on context it is used
func (m UserspbGenderValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
