// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserspbCreateUserRequest userspb create user request
//
// swagger:model userspb.CreateUserRequest
type UserspbCreateUserRequest struct {

	// email
	Email string `json:"email,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this userspb create user request
func (m *UserspbCreateUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this userspb create user request based on context it is used
func (m *UserspbCreateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserspbCreateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserspbCreateUserRequest) UnmarshalBinary(b []byte) error {
	var res UserspbCreateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
