// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserspbUpdateUserProfileData userspb update user profile data
//
// swagger:model userspb.UpdateUserProfileData
type UserspbUpdateUserProfileData struct {

	// avatar url
	// Example: /avatars/photo.jpg
	AvatarURL string `json:"avatar_url,omitempty"`

	// birth date
	// Example: 2001-11-23
	BirthDate string `json:"birth_date,omitempty"`

	// first name
	// Example: Ivan
	FirstName string `json:"first_name,omitempty"`

	// GENDER_UNSPECIFIED = 0 Reserved for Proto, not a valid value
	// GENDER_UNSELECTED = 1 User has not selected a gender
	// GENDER_MALE = 2 Represents male gender
	// GENDER_FEMALE = 3 Represents female gender
	// Example: 1
	GenderValue struct {
		UserspbGenderValue
	} `json:"gender_value,omitempty"`

	// last name
	// Example: Ivanov
	LastName string `json:"last_name,omitempty"`

	// middle name
	// Example: Olegovich
	MiddleName string `json:"middle_name,omitempty"`
}

// Validate validates this userspb update user profile data
func (m *UserspbUpdateUserProfileData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGenderValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserspbUpdateUserProfileData) validateGenderValue(formats strfmt.Registry) error {
	if swag.IsZero(m.GenderValue) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this userspb update user profile data based on the context it is used
func (m *UserspbUpdateUserProfileData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGenderValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserspbUpdateUserProfileData) contextValidateGenderValue(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *UserspbUpdateUserProfileData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserspbUpdateUserProfileData) UnmarshalBinary(b []byte) error {
	var res UserspbUpdateUserProfileData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
